#!/bin/tcsh -f
set my_editor="`printf "\""${0}"\"" | sed 's/.*\/\([^\:]\+\).*/\1/g'`"

if("${my_editor}" == "${0}" ) then
	echo "**error:** unable to determine session editor
your default editor will be used.";
	set my_editor="${EDITOR}";
endif

switch ( "${my_editor}" )
case "connectED":
case "gedit":
	breaksw
case "vi":
case "vim":
case "vim-enhanced":
default:
	set my_editor=`printf "%s -p" "vim-enhanced"`
	breaksw
endsw

${my_editor} "/projects/cli/console.pallet/tcshrc/alacast:environment.cshrc.tcsh" "/projects/cli/console.pallet/tcshrc/argv:clean-up" "/projects/cli/console.pallet/tcshrc/paths.cshrc.tcsh" "/projects/cli/console.pallet/tcshrc/source:argv";

 
