#!/bin/tcsh -f
if(! ${?eol} ) setenv eol '$';
while("${1}" != "" )
	while(! ${?ls_dir} )
		switch ("${1}")
			case "-l":
			case "--verbose":
			case "--print-path":
				set output="\5: \1\2\3\4\5\6";
				breaksw
			
			default:
				if(! -d "${1}" ) then
					printf "Usage: %s [-l, --verbose, --print-path] directory...\n" "`basename '${0}'`";
					exit -1;
				endif
				set ls_dir="${1}";
				breaksw
		
			endsw
		shift;
	end

	if(! ${?output} ) set output="\5: \1\6";
	
	printf "Contents of <%s>:\n" "`echo "\""${ls_dir}"\"" | sed -r 's/\/${eol}//'`";
	/bin/ls --width=1  "${ls_dir}" | /bin/sed -r "s/^(.*)(, released on)(:)?\ [^0-9,\ ]+,\ ( )?([0-9]+.*)(\.[^\.]*)${eol}/${output}/" | /bin/sort
	printf "\n";
	unset ls_dir;
end
