#!/bin/tcsh -f
if(! ${?0} ) then
	printf "Sourcing this script has been disabled.\n";
	set status=-1;
	exit ${status};
endif


while("${1}" != "" )
	while(! ${?search_directory} )
		switch ("${1}")
			case "-l":
			case "--verbose":
			case "--print-path":
				set output="\5: \1\2\3\4\5\6";
				breaksw;
			
			default:
				if(! -d "${1}" ) then
					printf "Usage: %s [-l, --verbose, --print-path] directory...\n" "`basename '${0}'`";
					exit -1;
				endif
				set search_directory="${1}";
				breaksw;
		
			endsw
		shift;
	end

	if(! ${?output} ) \
		set output="\5: \1\6";
	
	printf "Contents of <%s>:\n" "`echo "\""${search_directory}"\"" | sed -r 's/\/"\$"//'`";
	find "${search_directory}" -type f | \
		sed -r 's/(.*\/)(.*, released on\:? [^,]+, )([0-9]+ )(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)( [^.]+)(\.[^.]+)/\3\4\5\ \:\ \1\2\3\4\5\6/' \
		| sed -r 's/([0-9]+ )(Jan) ([0-9]+) ([^\:]+)(\:.*)/\3\-01\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Feb) ([0-9]+) ([^\:]+)(\:.*)/\3\-02\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Mar) ([0-9]+) ([^\:]+)(\:.*)/\3\-03\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Apr) ([0-9]+) ([^\:]+)(\:.*)/\3\-04\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(May) ([0-9]+) ([^\:]+)(\:.*)/\3\-05\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Jun) ([0-9]+) ([^\:]+)(\:.*)/\3\-06\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Jul) ([0-9]+) ([^\:]+)(\:.*)/\3\-07\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Aug) ([0-9]+) ([^\:]+)(\:.*)/\3\-08\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Sep) ([0-9]+) ([^\:]+)(\:.*)/\3\-09\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Oct) ([0-9]+) ([^\:]+)(\:.*)/\3\-10\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Nov) ([0-9]+) ([^\:]+)(\:.*)/\3\-11\-\1\4\5/' \
		| sed -r 's/([0-9]+ )(Dec) ([0-9]+) ([^\:]+)(\:.*)/\3\-12\-\1\4\5/' \
		| sort \
		| sed -r 's/(.*)\ \:\ (.*)/\2/' \
		| sed -r 's/(.*\/)(.*, released on\:? [^,]+, )([0-9]+ )([0-9]{4}\-[0-9]{2}\-[0-9]{2})( [^.]+)(\.[^.]+)/\3\ \:\ \1\2\3\4\5/' \
		| sort \
		| sed -r 's/(.*)\ \:\ (.*)/\2/' \
		> /dev/stdout;
	printf "\n";
	unset search_directory;
end
