#!/bin/tcsh -f
set label_current="init";
goto label_stack_set;
init:
	set label_current="init";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	set original_owd=${owd};
	set starting_dir=${cwd};
	set escaped_starting_cwd=${escaped_cwd};
	
	if(! $?0 ) \
		set being_sourced;
	
	set scripts_basename="mozilla:update:extentions";
	set scripts_alias="`printf '%s' '${scripts_basename}' | sed -r 's/(.*)\.(tcsh|cshrc)"\$"/\1/'`";
	
	set escaped_home_dir="`printf '%s' '${HOME}' | sed -r 's/\//\\\//g'`";
	
	if( "`alias cwdcmd`" != "" ) then
		set oldcwdcmd="`alias cwdcmd`";
		unalias cwdcmd;
	endif
	
	@ errno=0;
	
	#set supports_being_source;
	#set argz="";
	
	alias	ex	"ex -E -n -X --noplugin";
	
	#set download_command="curl";
	#set download_command_with_options="${download_command} --location --fail --show-error --silent --output";
	#alias	"curl"	"${download_command_with_options}";
	
	#set download_command="wget";
	#set download_command_with_options="${download_command} --no-check-certificate --quiet --continue --output-document";
	#alias	"wget"	"${download_command_with_options}";
	
	set mozilla_profiles_directory="/programs/mozilla/settings";
	
	goto parse_argv;
#init:

init_complete:
	set label_current="init_complete";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	set init_completed;
#init_complete:

check_dependencies:
	set label_current="check_dependencies";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	set dependencies=("${scripts_basename}");# "${scripts_alias}");
	@ dependencies_index=0;
#check_dependencies:


check_dependencies:
	set label_current="check_dependencies";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	foreach dependency(${dependencies})
		@ dependencies_index++;
		unset dependencies[$dependencies_index];
		foreach dependency("`where '${dependency}'`")
			if( ${?debug} ) \
				printf "\n**%s debug:** looking for dependency: %s.\n\n" "${scripts_basename}" "${dependency}"; 
			
			if(! -x "${dependency}" ) continue;
			
			if(! ${?scripts_dirname} ) then
				if("`basename '${dependency}'`" == "${scripts_basename}" ) then
					set old_owd="${cwd}";
					cd "`dirname '${dependency}'`";
					set scripts_dirname="${cwd}";
					cd "${owd}";
					set owd="${old_owd}";
					unset old_owd;
					set script="${scripts_dirname}/${scripts_basename}";
					if(! ${?TCSH_RC_SESSION_PATH} ) \
						setenv TCSH_RC_SESSION_PATH "${scripts_dirname}/../tcshrc";
					
					if(! ${?TCSH_LAUNCHER_PATH} ) \
						setenv TCSH_LAUNCHER_PATH \$"{TCSH_RC_SESSION_PATH}/../launchers";
				endif
			endif
			
			if( ${?debug} )	then
				switch( "`printf '%s' '${dependency}' | sed -r 's/.*([1-3])"\$"'/\1/`" )
					case "1":
						set suffix="st";
						breaksw;
					
					case "2":
						set suffix="nd";
						breaksw;
					
					case "3":
						set suffix="rd";
						breaksw;
					
					default:
						set suffix="th";
						breaksw;
				endsw
				
				printf "\n**%s debug:** found %d%s dependency: %s.\n\n" "${scripts_basename}" $dependencies_index "$suffix" "${dependency}";
				unset suffix;
			endif
			
			switch("${dependency}")
				case "${scripts_basename}":
				case "./${dependency}":
				case "${TCSH_LAUNCHER_PATH}/${dependency}":
					continue;
					breaksw;
			endsw
			break;
		end
		
		if(! ${?program} ) \
			set program="${script}";
		
		if(!( ${?dependency} && ${?script} && ${?program} )) then
			set missing_dependency;
		else
			if(!( -x ${script} && -x ${dependency} && -x ${program} )) \
				set missing_dependency;
		endif
		
		if( ${?missing_dependency} ) then
			@ errno=-501;
			goto exception_handler;
		endif
		
		unset dependency;
	end
	
	unset dependency dependencies;
#check_dependencies:


if_sourced:
	set label_current="if_sourced";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	if(! ${?being_sourced} ) \
		goto main;
	
	if(! ${?supports_being_source} ) \
		goto sourcing_disabled;
	
	goto sourcing_init;
#if_sourced:


sourcing_disabled:
	set label_current="sourcing_disabled";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	# BEGIN: disable source scripts_basename.  For exception handeling when this file is 'sourced'.
	@ errno=-502;
	goto exception_handler;
	# END: disable source scripts_basename.
#sourcing_disabled:


sourcing_init:
	set label_current="sourcing_init";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	# BEGIN: source scripts_basename support.
	source "${TCSH_RC_SESSION_PATH}/argv:check" "${scripts_basename}" ${argv};
#sourcing_init:


sourcing_main:
	set label_current="sourcing_main";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	# START: special handler for when this file is sourced.
	alias ${scripts_alias} \$"{TCSH_LAUNCHER_PATH}/${scripts_basename}";
	# FINISH: special handler for when this file is sourced.
#sourcing_main:


sourcing_main_quit:
	set label_current="sourcing_main_quit";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	source "${TCSH_RC_SESSION_PATH}/argv:clean-up" "${scripts_basename}";
	
	# END: source scripts_basename support.
	
	goto scripts_main_quit;
#sourcing_main_quit:


main:
	set label_current="main";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	alias	ex	"ex -E -n -X --noplugin";
#main:


exec:
	set label_current="exec";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	if( ${?debug} ) \
		printf "Executing %s's main.\n" "${scripts_basename}";
	
	if(! ${?mozilla_app} ) \
		set mozilla_app="firefox";
		
	if(! ${?mozilla_profile} ) \
		set mozill_profile="${USER}";
	
	if(!( -d "${mozilla_profiles_directory}/${mozilla_app}/profiles/${mozilla_profile}/extensions/" )) then
		@ errno=-503;
		goto exception_handler;
	endif
	
	set maxVersion="3";
	if(! ${?matchVersion} ) then
		if(! ${?update_all} ) then
			set matchVersion="[0-${maxVersion}]\.[^\*]";
		else
			set matchVersion="[0-9.]*";
		endif
	endif
	
	touch "${mozilla_profiles_directory}/${mozilla_app}/profiles/${mozilla_profile}/extensions/"*/install.rdf;
	
	foreach rdf ( "`egrep 'maxVersion[=\>]["\""]?(${matchVersion}[^"\""\<]*)["\""\<]' '${mozilla_profiles_directory}/${mozilla_app}/profiles/${mozilla_profile}/extensions/'*/install.rdf | sed -r 's/(.*):[\ \t]+.*/\1/' | sort | uniq`" )
		if(! -e "${rdf}" ) then
			printf "Unable to find %s(%s)\n" "${rdf}";
			continue;
		endif
		printf "Updating %s's maxVersion\n\n" "`/bin/grep --perl-regexp 'name[=\>]["\""'\'']?([^"\""'\''\<]*)["\""'\''\<]' "\""${rdf}"\"" | sed -r 's/.*name[=\>]["\""'\'']?([^"\""'\''\<]*)["\""'\''\<].*/\1/g'`";
		ex -X -n -E --noplugin "+1,"\$"s/\v(maxVersion[\=\>])(["\""']?)([^"\""'\<]*)(["\""'\<])/\1\2${maxVersion}\.\*\4" '+wq!' "${rdf}" > /dev/null;
	end
	goto scripts_main_quit;
#exec:


scripts_main_quit:
	set label_current="scripts_main_quit";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	if( ${?label_current} ) \
		unset label_current;
	if( ${?label_previous} ) \
		unset label_previous;
	if( ${?labels_previous} ) \
		unset labels_previous;
	if( ${?label_next} ) \
		unset label_next;
	
	if( ${?argc} ) \
		unset argc;
	if( ${?argz} ) \
		unset argz;
	if( ${?parsed_arg} ) \
		unset parsed_arg;
	if( ${?parsed_argv} ) \
		unset parsed_argv;
	if( ${?parsed_argc} ) \
		unset parsed_argc;
	
	if( ${?init_completed} ) \
		unset init_completed;
	
	if( ${?being_sourced} ) \
		unset being_sourced;
	if( ${?supports_being_source} ) \
		unset supports_being_source;
	
	if( ${?script} ) \
		unset script;
	if( ${?scripts_alias} ) \
		unset scripts_alias;
	if( ${?scripts_basename} ) \
		unset scripts_basename;
	if( ${?scripts_dirname} ) \
		unset scripts_dirname;
	
	if( ${?debug} ) \
		unset debug;
	
	if( ${?dependency} ) \
		unset dependency;
	if( ${?dependencies} ) \
		unset dependencies;
	if( ${?missing_dependency} ) \
		unset missing_dependency;
	
	if( ${?usage_displayed} ) \
		unset usage_displayed;
	if( ${?no_exit_on_usage} ) \
		unset no_exit_on_usage;
	if( ${?display_usage_on_error} ) \
		unset display_usage_on_error;
	if( ${?last_exception_handled} ) \
		unset last_exception_handled;
	
	if( ${?label_previous} ) \
		unset label_previous;
	if( ${?label_next} ) \
		unset label_next;
	
	if( ${?callback} ) \
		unset callback;
	if( ${?last_callback} ) \
		unset last_callback;
	if( ${?callback_stack} ) \
		unset callback_stack;
	
	if( ${?argc_required} ) \
		unset argc_required;
	if( ${?arg_shifted} ) 					\
		unset arg_shifted;
	
	if( ${?escaped_cwd} ) \
		unset escaped_cwd;
	if( ${?escaped_home_dir} ) \
		unset escaped_home_dir;
	if( ${?escaped_starting_cwd} ) \
		unset escaped_starting_cwd;
	
	if( ${?old_owd} ) \
		unset old_owd;
	
	if( ${?starting_cwd} ) then
		if( "${starting_cwd}" != "${cwd}" ) \
			cd "${starting_cwd}";
	endif
	
	if( ${?original_owd} ) then
		set owd="${original_owd}";
		unset original_owd;
	endif
	
	if( ${?oldcwdcmd} ) then
		alias cwdcmd "${oldcwdcmd}";
		unset oldcwdcmd;
	endif
	
	if(! ${?errno} ) then
		set status=0;
	else
		set status=$errno;
		unset errno;
	endif
	exit ${status}
#scripts_main_quit:


usage:
	set label_current="usage";
	if( "${label_next}" != "${label_current}" ) \
		goto label_stack_set;
	
	if( ${?errno} ) then
		if( ${errno} != 0 ) then
			if(! ${?last_exception_handled} ) \
				set last_exception_handled=0;
			if( ${last_exception_handled} != ${errno} ) then
				if(! ${?callback} ) \
					set callback="usage";
				goto exception_handler;
			endif
		endif
	endif
	
	if(! ${?script} ) then
		printf "Usage:\n\t%s [options]\n\tPossible options are:\n\t\t[-h|--help]\tDisplays this screen.\n" "${scripts_basename}";
	else if( "${program}" != "${script}" ) then
		${program} --help;
	endif
	
	if(! ${?usage_displayed} ) \
		set usage_displayed;
	
	if(! ${?no_exit_on_usage} ) \
		goto scripts_main_quit;
	
	if(! ${?callback} ) \
		set callback="parse_arg";
	goto callback_handler;
#usage:


exception_handler:
	set label_current="exception_handler";
	if( "${label_next}" != "${label_current}" ) \
		goto label_stack_set;
	
	if(! ${?errno} ) \
		@ errno=-599;
	printf "\n**%s error("\$"errno:%d):**\n\t" "${scripts_basename}"  $errno;
	switch( $errno )
		case -500:
			printf "Debug mode has triggered an exception for diagnosis.  Please see any output above.\n" "${scripts_basename}" > /dev/stderr;
			@ errno=0;
			breaksw;
		
		case -501:
			printf "One or more required dependencies couldn't be found.\n\t[%s] couldn't be found.\n\t%s requires: %s" "${dependency}" "${scripts_basename}" "${dependencies}";
			breaksw;
		
		case -502:
			printf "Sourcing is not supported and may only be executed" > /dev/stderr;
			breaksw;
		
		case -503:
			printf "An internal script error has caused an exception.  Please see any output above" > /dev/stderr;
			if(! ${?debug} ) \
				printf " or run: %s%s --debug%s to find where %s failed" '`' "${scripts_basename}" '`' "${scripts_basename}" > /dev/stderr;
			printf ".\n" > /dev/stderr;
			breaksw;
		
		case -504:
			printf "One or more required options have not been provided." > /dev/stderr;
			breaksw;
		
		case -505:
			printf "%s%s is an unsupported option.\n\tRun %s%s --help%s for supported options and details" "${dashes}" "${option}" '`' "${scripts_basename}" '`' > /dev/stderr;
			breaksw;
		
		case -599:
		default:
			printf "An unknown error "\$"errno: %s has occured" "${errno}" > /dev/stderr;
			breaksw;
	endsw
	set last_exception_handled=$errno;
	printf "\nrun: %s%s --help%s for more information\n" '`' "${scripts_basename}" '`' > /dev/stderr;
	
	if( ${?display_usage_on_error} ) \
		goto usage;
	
	if( ${?callback} ) \
		goto callback_handler;
	
	goto scripts_main_quit;
#exception_handler:



parse_argv:
	set label_current="parse_argv";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	if( ${?init_completed} ) then
		if(! ${?being_sourced} ) then
			set callback="exec";
		else
			set callback="sourcing_main";
		endif
		goto callback_handler;
	endif
	
	@ argc=${#argv};
	@ required_options=2;
	
	if( ${argc} < ${required_options} ) then
		@ errno=-504;
		set callback="parse_argv_quit";
		goto exception_handler;
	endif
	
	@ arg=0;
	while( $arg < $argc )
		@ arg++;
		switch("$argv[$arg]")
			case "--diagnosis":
			case "--diagnostic-mode":
				printf "**%s debug:**, via "\$"argv[%d], diagnostic mode\t[enabled].\n\n" "${scripts_basename}" $arg;
				set diagnostic_mode;
				break;
			
			case "--debug":
				printf "**%s debug:**, via "\$"argv[%d], debug mode\t[enabled].\n\n" "${scripts_basename}" $arg;
				set debug;
				break;
			
			default:
				continue;
		endsw
	end
	
	if( ${?debug} || ${?diagnostic_mode} ) \
		printf "**%s debug:** checking argv.  %d total arguments.\n\n" "${scripts_basename}" "${argc}";
	
	set mozilla_apps=("firefox" "thunderbird" "xulrunner" "seamonkey");
	
	@ arg=0;
	@ parsed_argc=0;
#parse_argv:

parse_arg:
	set label_current="parse_arg";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	while( $arg < $argc )
		if(! ${?arg_shifted} ) \
			@ arg++;
		
		if( ${?debug} || ${?diagnostic_mode} ) \
			printf "**%s debug:** Checking argv #%d (%s).\n" "${scripts_basename}" "${arg}" "$argv[$arg]";
		
		set dashes="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\1/'`";
		if( "${dashes}" == "$argv[$arg]" ) set dashes="";
		
		set option="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\2/'`";
		if( "${option}" == "$argv[$arg]" ) set option="";
		
		set equals="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\3/'`";
		if( "${equals}" == "$argv[$arg]" || "${equals}" == "" ) set equals="";
		
		set equals="";
		set value="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\4/'`";
		if( "${value}" != "" && "${value}" != "$argv[$arg]" ) then
			set equals="=";
		else if( "${option}" != "" ) then
			@ arg++;
			if( ${arg} > ${argc} ) then
				@ arg--;
			else
				set test_dashes="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\1/'`";
				set test_option="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\2/'`";
				set test_equals="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\3/'`";
				set test_value="`printf "\""$argv[$arg]"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(=?)['\''"\""]?(.*)['\''"\""]?"\$"/\4/'`";
				
				if( ${?debug} || ${?diagnostic_mode} ) \
					printf "\tparsed %sargv[%d] (%s) to test for replacement value.\n\tparsed %stest_dashes: [%s]; %stest_option: [%s]; %stest_equals: [%s]; %stest_value: [%s]\n" \$ "${arg}" "$argv[$arg]" \$ "${test_dashes}" \$ "${test_option}" \$ "${test_equals}" \$ "${test_value}";
				
				if(!("${test_dashes}" == "$argv[$arg]" && "${test_option}" == "$argv[$arg]" && "${test_equals}" == "$argv[$arg]" && "${test_value}" == "$argv[$arg]")) then
					@ arg--;
				else
					set equals="=";
					set value="$argv[$arg]";
					set arg_shifted;
				endif
				unset test_dashes test_option test_equals test_value;
			endif
		endif
		
		if( "`printf "\""${value}"\"" | sed -r "\""s/^(~)(.*)/\1/"\""`" == "~" ) then
			set value="`printf "\""${value}"\"" | sed -r "\""s/^(~)(.*)/${escaped_home_dir}\2/"\""`";
		endif
		
		if( "`printf "\""${value}"\"" | sed -r "\""s/^(\.)(.*)/\1/"\""`" == "." ) then
			set value="`printf "\""${value}"\"" | sed -r "\""s/^(\.)(.*)/${escaped_starting_cwd}\2/"\""`";
		endif
		
		@ parsed_argc++;
		set parsed_arg="${dashes}${option}${equals}${value}";
		if(! ${?parsed_argv} ) then
			set parsed_argv="${parsed_arg}";
		else
			set parsed_argv="${parsed_argv} ${parsed_arg}";
		endif
		
		if( ${?debug} || ${?diagnostic_mode} ) \
			printf "\tparsed option %sparsed_argv[%d]: %s\n" \$ "$parsed_argc" "${parsed_arg}";
		
		switch("${option}")
			case "numbered_option":
				if(! ( "${value}" != "" && ${value} > 0 )) then
					printf "%s%s must be followed by a valid number greater than zero." "${dashes}" "${option}";
					breaksw;
				endif
				
				set numbered_option="${value}";
				breaksw;
			
			case "h":
			case "help":
				goto usage;
				breaksw;
			
			case "verbose":
				if(! ${?be_verbose} ) set be_verbose;
				breaksw;
			
			case "debug":
				if(! ${?debug} ) set debug;
				breaksw;
			
			case "firefox":
			case "thunderbird":
			case "xulrunner":
			case "seamonkey":
				set mozilla_app="${value}";
				breaksw;
			
			case "app":
				foreach app(${mozilla_apps})
					if( "${value}" == "${app}" ) \
						break;
					unset app;
				end
				
				if(! ${?app} ) then
					@ errno=-1;
					goto exception_handler;
				endif
				
				set mozilla_app="${value}";
				breaksw;
			
			case "profile":
				foreach app(${mozilla_apps})
					if( -d "${mozilla_profiles_directory}/${app}/profiles/${value}/extensions/" ) \
						break;
					unset app;
				end
				
				if(! ${?app} ) then
					@ errno=-2;
					goto exception_handler;
				endif
				
				set mozilla_profile="${value}";
				breaksw;
			
			case "diagnosis":
			case "diagnostic-mode":
				if( ${?diagnostic_mode} ) \
					breaksw;
				
				printf "**%s debug:**, via "\$"argv[%d], diagnostic mode\t[enabled].\n\n" "${scripts_basename}" $arg;
				set diagnostic_mode;
				breaksw;
			
			case "f":
			case "force":
			case "update-all":
			cass "all-extensions":
				if(! ${?update_all} ) \
					set update_all;
				breaksw;
			
			case "update":
				switch("${value}")
					case "all":
					case "all-extensions":
						if(! ${?update_all} ) \
							set update_all;
					breaksw;
					
					default:
						if(! ( "${value}" != "" && ${value} > 0 )) then
							printf "%s%s must be a valid number greater than zero." "${dashes}" "${option}";
							breaksw;
						endif
						set matchVersion="${value}";
						breaksw;
				endsw
				breaksw;
			
			case "enable":
				switch("${value}")
					case "verbose":
						if(! ${?be_verbose} ) \
							breaksw;
						
						printf "**%s debug:**, via "\$"argv[%d], verbose output\t[enabled].\n\n" "${scripts_basename}" $arg;
						set be_verbose;
						breaksw;
					
					case "debug":
						if( ${?debug} ) \
							breaksw;
						
						printf "**%s debug:**, via "\$"argv[%d], debug mode\t[enabled].\n\n" "${scripts_basename}" $arg;
						set debug;
						breaksw;
					
					case "diagnosis":
					case "diagnostic-mode":
						if( ${?diagnostic_mode} ) \
							breaksw;
						
						
						printf "**%s debug:**, via "\$"argv[%d], diagnostic mode\t[enabled].\n\n" "${scripts_basename}" $arg;
						set diagnostic_mode;
						breaksw;
					
					case "update-all":
						if(! ${?update_all} ) \
							set update_all;
						breaksw;
					
					default:
						printf "enabling %s is not supported by %s.  See %s --help\n" "${value}" "${scripts_basename}" "${scripts_basename}";
						breaksw;
				endsw
				breaksw;
			
			case "disable":
				switch("${value}")
					case "verbose":
						if(! ${?be_verbose} ) \
							breaksw;
						
						printf "**%s debug:**, via "\$"argv[%d], verbose output\t[disabled].\n\n" "${scripts_basename}" $arg;
						unset be_verbose;
						breaksw;
					
					case "debug":
						if(! ${?debug} ) \
							breaksw;
						
						printf "**%s debug:**, via "\$"argv[%d], debug mode\t[disabled].\n\n" "${scripts_basename}" $arg;
						unset debug;
						breaksw;
					
					case "diagnosis":
					case "diagnostic-mode":
						if(! ${?diagnostic_mode} ) \
							breaksw;
						
						printf "**%s debug:**, via "\$"argv[%d], diagnostic mode\t[disabled].\n\n" "${scripts_basename}" $arg;
						unset diagnostic_mode;
						breaksw;
					
					case "update-all":
						if( ${?update_all} ) \
							unset update_all;
						breaksw;
					
					default:
						printf "disabling %s is not supported by %s.  See %s --help\n" "${value}" "${scripts_basename}" "${scripts_basename}";
						breaksw;
				endsw
				breaksw;
			
			default:
				if(! ${?mozilla_app} ) then
					foreach app(${mozilla_apps})
						if( "$argv[$arg]" == "${app}" ) \
							break;
						
						unset app;
					end
					if(${?app}) then
						set mozilla_app="${app}";
						unset app;
						continue;
					endif
				endif
				
				if(! ${?mozilla_profile} ) then
					if( ${?mozilla_app} ) then
						if( -d "${mozilla_profiles_directory}/${mozilla_app}/profiles/$argv[$arg]/extensions/" ) \
							set app="${mozilla_app}";
					else
						foreach app(${mozilla_apps})
							if( -d "${mozilla_profiles_directory}/${app}/profiles/$argv[$arg]/extensions/" ) \
								break;
							
							unset app;
						end
					endif
					
					if(${?app}) then
						set mozilla_profile="$argv[$arg]";
						unset app;
						continue;
					endif
				endif
				
				if(! ${?argz} ) then
					@ errno=-505;
					set callback="parse_arg";
					goto exception_handler;
					breaksw;
				endif
				
				if( "${argz}" == "" ) then
					set argz="$parsed_arg";
				else
					set argz="${argz} $parsed_arg";
				endif
				breaksw;
		endsw
		
		if( ${?arg_shifted} ) then
			unset arg_shifted;
			@ arg--;
		endif
		
		unset dashes option equals value parsed_arg;
	end
#parse_arg:


parse_argv_quit:
	set label_current="parse_argv_quit";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	if(! ${?callback} ) then
		unset arg argc;
	else
		if( "${callback}" != "parse_arg" ) then
			unset arg;
		endif
	endif
	if( ${?diagnostic_mode} ) then
		set callback="diagnostic_mode";
	else
		if(! ${?callback} ) then
			if(! ${?init_completed} ) then
				set callback="init_complete";
			else if(! ${?being_sourced} ) then
				set callback="exec";
			else
				set callback="sourcing_main";
			endif
		endif
	endif
	
	goto callback_handler;
#parse_argv_quit:


label_stack_set:
	if( ${?current_cwd} ) then
		if( ${current_cwd} != ${cwd} ) \
			cd ${current_cwd};
		unset current_cwd;
	endif
	
	if( ${?old_owd} ) then
		if( ${old_owd} != ${owd} ) then
			set owd=${old_owd};
		endif
	endif
	
	set old_owd="${owd}";
	set current_cwd="${cwd}";
	set escaped_cwd="`printf '%s' '${cwd}' | sed -r 's/\//\\\//g'`";
	#set escaped_cwd="`printf ${cwd} | sed -r 's/(['\''"\""\ \<\>\(\)\&\|\!\?\*\+\-])/\\\1/g'`";
	
	set label_next=${label_current};
	
	if(! ${?labels_previous} ) then
		set labels_previous=("${label_current}");
		set label_previous="$labels_previous[${#labels_previous}]";
	else
		if("${label_current}" != "$labels_previous[${#labels_previous}]" ) then
			set labels_previous=($labels_previous "${label_current}");
			set label_previous="$labels_previous[${#labels_previous}]";
		else
			set label_previous="$labels_previous[${#labels_previous}]";
			unset labels_previous[${#labels_previous}];
		endif
	endif
	
	#set label_previous=${label_current};
	
	set callback=${label_previous};
	
	if( ${?debug} || ${?diagnostic_mode} ) \
		printf "handling label_current: [%s]; label_previous: [%s].\n" "${label_current}" "${label_previous}" > /dev/stdout;
	
	#unset label_previous;
	#unset label_current;
	
	goto callback_handler;
#label_stack_set:


callback_handler:
	if(! ${?callback} ) \
		goto scripts_main_quit;
	
	if(! ${?callback_stack} ) then
		set callback_stack=("${callback}");
		set last_callback="$callback_stack[${#callback_stack}]";
	else
		if("${callback}" != "$callback_stack[${#callback_stack}]" ) then
			set callback_stack=($callback_stack "${callback}");
			set last_callback="$callback_stack[${#callback_stack}]";
		else
			set last_callback="$callback_stack[${#callback_stack}]";
			unset callback_stack[${#callback_stack}];
		endif
		unset callback;
	endif
	if( ${?debug} || ${?diagnostic_mode} ) \
		printf "handling callback to [%s].\n" "${last_callback}" > /dev/stdout;
	
	goto $last_callback;
#callback_handler:


diagnostic_mode:
	set label_current="diagnostic_mode";
	if( "${label_current}" != "${label_previous}" ) \
		goto label_stack_set;
	
	if( -e "/tmp/${scripts_basename}-debug.log" ) rm -v "/tmp/${scripts_basename}-debug.log";
	touch "/tmp/${scripts_basename}-debug.log";
	printf "----------------%s debug.log-----------------\n" "${scripts_basename}" >> "/tmp/${scripts_basename}-debug.log";
	printf \$"argv:\n\t%s\n\n" "$argv" >> "/tmp/${scripts_basename}-debug.log";
	printf \$"parsed_argv:\n\t%s\n\n" "$parsed_argv" >> "/tmp/${scripts_basename}-debug.log";
	printf \$"{0} == [%s]\n" "${0}" >> "/tmp/${scripts_basename}-debug.log";
	@ arg=0;
	while( "${1}" != "" )
		@ arg++;
		printf \$"{%d} == [%s]\n" $arg "${1}" >> "/tmp/${scripts_basename}-debug.log";
		shift;
	end
	printf "\n\n----------------<%s> environment-----------------\n" "${scripts_basename}" >> "/tmp/${scripts_basename}-debug.log";
	env >> "/tmp/${scripts_basename}-debug.log";
	printf "\n\n----------------<%s> variables-----------------\n" "${scripts_basename}" >> "/tmp/${scripts_basename}-debug.log";
	set >> "/tmp/${scripts_basename}-debug.log";
	printf "Create %s debug log:\n\t/tmp/%s-debug.log\n" "${scripts_basename}" "${scripts_basename}";
	@ errno=-500;
	set callback="sourcing_main_quit";
	goto exception_handler;
#diagnostic_mode:


