#!/bin/tcsh -f
	onintr exit_script;
	if(! ${?TCSH_ALTERNATIVES_PATH} ) \
		setenv TCSH_ALTERNATIVES_PATH \$"{TCSH_RC_SESSION_PATH}/../launchers";


	set scripts_basename="renice";
	
	if( ${?script} ) \
		unset script;
	if( ${?scripts_exec} ) \
		unset scripts_exec;
	
	
	@ dependencies_index=0;
	set dependencies=("${scripts_basename}" "renice" );
	while( $dependencies_index < ${#dependencies} )
		@ dependencies_index++;
		set dependency=$dependencies[$dependencies_index];
		if( ${?debug} ) \
			printf "\n**%s debug:** looking for dependency: %s; "\$"dependencies[%d].\n\n" "${scripts_basename}" "${dependency}" $dependencies_index > ${stdout};
		
		foreach exec("`where '${dependency}'`")
			if(! -x "${exec}" ) then
				unset exec;
				continue;
			endif
			
			#if( ${?debug} ) \
				printf "\n**%s debug:** looking for dependency: %s, "\$"dependencies[%d], against: %s.\n\n" "${scripts_basename}" "${dependency}" $dependencies_index "${exec}" > ${stdout};
			switch("${exec}")
				case "${scripts_basename}":
				case "${TCSH_ALTERNATIVES_PATH}/${scripts_basename}":
					if( ${?script} ) \
						breaksw;
						
					set old_owd="${cwd}";
					cd "`dirname '${exec}'`";
					set scripts_path="${cwd}";
					cd "${owd}";
					set owd="${old_owd}";
					unset old_owd;
					set script="${scripts_path}/${scripts_basename}";
					breaksw;
				
				case "/bin/${dependency}":
				case "/usr/bin/${dependency}":
				case "/usr/share/bin/${dependency}":
				case "/usr/local/bin/${dependency}":
					#if( ${?debug} ) \
						printf "\n**%s debug:** setting scripts binary.\n\tdependency: %s, "\$"dependencies[%d], binary: %s.\n\n" "${scripts_basename}" "${dependency}" $dependencies_index "${exec}" > ${stdout};
					switch( "${dependency}" )
						case "${scripts_basename}":
							if(! ${?scripts_exec} ) \
								set scripts_exec="${exec}";
							breaksw;
					endsw
					breaksw;
				
				default:
					breaksw;
			endsw
			unset exec;
		end
	end
	
	if(! ${?scripts_exec} ) \
		goto missing_dependency;
	
	if(! -x "${scripts_exec}" ) \
		goto missing_dependency;
		
	unset dependency dependencies;
#goto ependencies_check;

if(! ${?0} ) then
	alias "${scripts_basename}"	\$"{TCSH_ALTERNATIVES_PATH}/${scripts_basename}";
	complete ${scripts_basename} 'p/1/(-19 -18 -17 -16 -15 -14 -13 -12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 +1 +2 +3 +4 +5 +6 +7 +8 +9 +10 +11 +12 +13 +14 +15 +16 +17 +18 +19 +20)/' 'p/2-/c/'
	goto main_quit;
endif

goto launchers_main;


missing_dependency:
	printf "One or more required dependencies couldn't be found.\n\n[%s] couldn't be found.\n\n%s requires: %s" "${dependency}" "${scripts_basename}" "${dependencies}";
	set status=-1;
	goto exit_script;
#goto missing_dependency;


exit_script:
	onintr main_quit;
	goto main_quit;
#goto main_quit;


main_quit:
	if( ${?dependencies_index} ) \
		unset dependencies_index;
	if( ${?pid} ) \
		unset pid;
	if( ${?priority} ) \
		unset priority;
	if( ${?script} ) \
		unset script;
	if( ${?scripts_exec} ) \
		unset scripts_exec;
	if( ${?scripts_path} ) \
		unset scripts_path;
	if( ${?dependencies} )\
		unset dependencies;
	if( ${?scripts_basename} )\
		unset scripts_basename;
	if( ${?dependency} ) \
		unset dependency;
	if( ${?program} ) \
		unset program;
	if( ${?scripts_basename} ) \
		unset scripts_basename;
	exit ${status};
#main_quit

usage:
	printf "%s priority pid" "${scripts_basename}";
	goto main_quit;
#usage:

launchers_main:
	while( "${1}" != "" )
		if( "${1}" == "--help" || "${1}" == "-h" ) then
			goto usage;
		else if(! ${?priority} ) then
			if( `printf "${1}" | sed -r 's/^[\+\-]?[0-9]+$//'` == "" ) \
				set priority="${1}";
		else if(! ${?pid} ) then
			if( `printf "${1}" | sed -r 's/^[0-9]+$//'` == "" ) \
				set pid="${1}";
		endif
		
		shift;
	end
	
	if(!( ${?priority} && ${?pid} )) \
		goto usage;
	
	if( $uid != 0 && `printf "${priority}" | sed -r 's/^(.).*$/\1/'` == "-" ) \
		set program="sudo ${program}";
	
	echo ${program} ${priority} ${pid};
	${program} ${priority} ${pid};

	unset scripts_basename program;
	goto main_quit;
#goto launchers_main;

