#!/bin/tcsh -f
init:
	if( ${?SSH_CONNECTION} ) then
		set stdout=/dev/null;
		set stderr=/dev/null;
	else
		set stdout=/dev/stdout;
		set stderr=/dev/stderr;
	endif
	
	set supports_being_source;
	set scripts_basename="touch";
	set scripts_tmpdir="/tmp";
	
	alias ex "ex -E -n -X --noplugin";
	
	set escaped_starting_dir="`printf "\""%s"\"" "\""${cwd}"\"" | sed -r 's/\//\\\//g' | sed -r 's/(["\""])/"\""\\"\"""\""/g' | sed -r 's/([*])/\\\1/g' | sed -r 's/(['\!'])/\\\1/g'`";
	set escaped_home_dir="`printf "\""%s"\"" "\""${HOME}"\"" | sed -r 's/\//\\\//g' | sed -r 's/(["\""])/"\""\\"\"""\""/g' | sed -r 's/([*])/\\\1/g' | sed -r 's/(['\!'])/\\\1/g'`";
#goto init;

debug_check:
	@ arg=0;
	@ argc=${#argv};
	
	@ minimum_options=1;
	if( ${?minimum_options} ) then
		if( ${minimum_options} > 0 && ${#argv} < ${minimum_options} ) then
			@ errno=-503;
			printf "One or more required options have not been provided." > ${stderr};
			goto exit_script;
		endif
	endif
	
	#@ maximum_options=2;
	if( ${?maximum_options} ) then
		if( ${maximum_options} > 0 && ${#argv} > ${maximum_options} ) then
			@ errno=-504;
			printf "To many options have been provided." > ${stderr};
			goto exit_script;
		endif
	endif
	
	while( $arg < $argc )
		@ arg++;
		
		set argument_file="${scripts_tmpdir}/.escaped.argument.${scripts_basename}.argv[${arg}].`date '+%s'`.arg";
		printf "%s" "$argv[${arg}]" >! "${argument_file}";
		ex -s '+s/\v([\"\!\$\`])/\"\\\1\"/g' '+wq!' "${argument_file}";
		set escaped_argument="`cat "\""${argument_file}"\""`";
		rm -f "${argument_file}";
		unset argument_file;
		set argument="`printf "\""%s"\"" "\""${escaped_argument}"\""`";
		
		set option="`printf "\""%s"\"" "\""${escaped_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\2/'`";
		if( "${option}" == "${argument}" ) \
			set option="";
		
		set value="`printf "\""%s"\"" "\""${escaped_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\4/'`";
		if( -e "${value}" ) \
			continue;
		
		if( ${?debug} || ${?debug_arguments} ) \
			printf "**%s debug_check:**"\$"option: [${option}]; "\$"value: [${value}].\n" "${scripts_basename}" > ${stdout};
		
		switch("${option}")
			case "nodeps":
				if( ${?nodeps} ) \
					breaksw;
				
				set nodeps;
				
				if( "${value}" != "" ) \
					set value="";
				
				breaksw;
			
			case "diagnosis":
			case "diagnostic-mode":
				if( ${?diagnosis} ) \
					continue;
				
				printf "**%s debug:**, via "\$"argv[%d], diagnostic mode:\t[enabled].\n\n" "${scripts_basename}" ${arg} > ${stdout};
				set diagnosis;
				if(! ${?debug} ) \
					set debug;
				
				if( "${value}" != "" ) \
					set value="";
				
				breaksw;
			
			case "debug":
				switch("${value}")
					case "logged":
						if( ${?debug_logged} ) \
							continue;
						
						set debug_logged;
						breaksw;
					
					case "dependencies":
						if( ${?debug_dependencies} ) \
							continue;
						
						set debug_dependencies;
						breaksw;
					
					case "arguments":
						if( ${?debug_arguments} ) \
							continue;
						
						set debug_arguments;
						breaksw;
					
					case "stdin":
						if( ${?debug_stdin} ) \
							continue;
						
						set debug_stdin;
						breaksw;
					
					case "filenames":
						if(! ${?supports_multiple_files} ) then
							printf "**%s notice:** does not support handling or processing multiple files.\n" "${scripts_basename}" > ${stderr};
							printf "**%s notice:**, via "\$"argv[%d], debugging %s:\t[unsupported].\n" "${scripts_basename}" ${arg} "${value}" > ${stderr};
							continue;
						endif
						
						if( ${?debug_filenames} ) \
							continue;
						
						set debug_filenames;
						breaksw;
					
					default:
						if( ${?debug} ) \
							continue;
						
						if( "${value}" != "" ) \
							set value="";
						
						set debug;
						breaksw;
				endsw
			default:
				continue;
		endsw
		
		printf "**%s notice:**, via "\$"argv[%d], %s mode" "${scripts_basename}" ${arg} "${option}" > ${stdout};
		if( "${value}" != "" ) \
			printf " %s" "${value}" > ${stdout};
		
		if( "${option}" == "debug" ) \
			printf " debugging" > ${stdout};
		
		printf ":\t[enabled].\n\n" > ${stdout};
	end
#goto debug_check;


dependencies_check:
	set dependencies=("${scripts_basename}" "touch" "chmod");
	@ dependencies_index=0;
	
	while( $dependencies_index < ${#dependencies} )
		@ dependencies_index++;
		set dependency=$dependencies[$dependencies_index];
		if( ${?debug} ) \
			printf "\n**%s debug:** looking for dependency: %s; "\$"dependencies[%d].\n\n" "${scripts_basename}" "${dependency}" $dependencies_index > ${stdout};
		
		foreach exec("`where '${dependency}'`")
			if(! -x "${exec}" ) then
				unset exec;
				continue;
			endif
			
			if( ${?debug} ) \
				printf "\n**%s debug:** looking for dependency: %s, "\$"dependencies[%d], against: %s.\n\n" "${scripts_basename}" "${dependency}" $dependencies_index "${exec}" > ${stdout};
			switch("${exec}")
				case "${scripts_basename}":
				case "${TCSH_ALTERNATIVES_PATH}/${scripts_basename}":
					if( ${?script} ) \
						breaksw;
						
					set old_owd="${cwd}";
					cd "`dirname '${exec}'`";
					set scripts_path="${cwd}";
					cd "${owd}";
					set owd="${old_owd}";
					unset old_owd;
					set script="${scripts_path}/${scripts_basename}";
					breaksw;
				
				case "/bin/${dependency}":
				case "/usr/bin/${dependency}":
				case "/usr/share/bin/${dependency}":
				case "/usr/local/bin/${dependency}":
					switch( "${dependency}" )
						case "${scripts_basename}":
							if(! ${?scripts_exec} ) \
								set scripts_exec="${exec}";
							breaksw;
						
						case "chmod":
							if(! ${?chmod_exec} ) \
								set chmod_exec="${exec}";
							breaksw;
					endsw
					breaksw;
				
				default:
					breaksw;
			endsw
			unset exec;
		end
	end
	
	if(! ${?scripts_exec} ) \
		goto missing_dependency;
	
	if(! -x "${scripts_exec}" ) \
		goto missing_dependency;
		
	if(! ${?chmod_exec} ) \
		goto missing_dependency;
	
	if(! -x "${chmod_exec}" ) \
		goto missing_dependency;
	
	unset dependency dependencies;
#goto ependencies_check;


if_sourced:
	if( ${?0} ) \
		goto main;
	
	# for exception handeling when this file is 'sourced'.
	
	# BEGIN: disable source scripts_basename.
	if(! ${?supports_being_source} ) then
		set status=-1;
		printf "%s does not support being sourced.\n" "${scripts_basename}";
		goto exit_script;
	endif
	# END: disable source scripts_basename.
	
	# BEGIN: source scripts_basename support.
	if( -d "${scripts_path}/../tcshrc" && -f "${scripts_path}/../tcshrc/argv:check" ) \
		source "${scripts_path}/argv:check" "${scripts_basename}" ${argv};
	
	# START: special handler for when this file is sourced.
	if( `alias "${scripts_basename}"` != "" ) then
		set alias_argz=" `alias "\""${scripts_basename}"\"" | sed -r 's/^([^ ]+) (.*)/\2/'`";;
	else
		set alias_argz;
	endif
	
	alias ${scripts_basename} "${script}${alias_argz}";
	
	unset alias_argz;
	# FINISH: special handler for when this file is sourced.
	
	# END: source support.
	
	goto exit_script;
#goto if_sourced;


main:
	set argc=${#argv};
	
	goto parse_argv; # exit's via 'usage:' or 'exec:'.
#goto main;


exec:
	set status=0;
	sort "${touch_targets}" | uniq >! "${touch_targets}.pso";
	mv -f "${touch_targets}.pso" "${touch_targets}";
	
	foreach escaped_touch_target("`cat "\""${touch_targets}"\"" | sed -r 's/(["\"\$\!\`"])/"\""\\\1"\""/g'`")
		ex -s '+1d' '+wq!' "${touch_targets}";
		set touch_target="`printf "\""%s"\"" "\""${escaped_touch_target}"\""`";
		
		if(! ${?no_mk_path} ) then
			set touch_dir="`dirname "\""${escaped_touch_target}"\""`";
			if(! -d "${touch_dir}" ) then
				if(! ${?be_vebose} ) then
					mkdir -p "${touch_dir}";
				else
					mkdir -pv "${touch_dir}";
				endif
			endif
			unset touch_dir;
		endif
	
		if( ${?debug} ) then
			printf "( %s %s "\""%s"\"" > %s ) >& %s;\n" "${scripts_exec}" "${argz}" "${touch_target}" "${stdout}" "${stderr}" > ${stdout};
		else if( ${?be_verbose} ) then
			printf "touch: creating <file://%s>\n" "${touch_target}";
		endif
		( ${scripts_exec} ${argz} "${touch_target}" > ${stdout} ) >& ${stderr};
		
		if( ${?mode} ) then
			if( ${?debug} ) then
				printf "( %s %s "\""%s"\"" > %s ) >& %s;" "${chmod_exec}" "${mode}" "${touch_target}" "${stdout}" "${stderr}" > ${stdout};
			else if( ${?be_verbose} ) then
				printf "touch: setting mode of <file://%s> to [%s].\n" "${touch_target}" "${mode}";
			endif
			( ${chmod_exec} ${mode} "${touch_target}" > ${stdout} ) >& ${stderr};
		endif
		unset touch_target;
	end
	
	goto exit_script;
#goto exec;


exit_script:
	onintr scripts_main_quit;
	goto scripts_main_quit;
#goto exit_script;


scripts_main_quit:
	if( ! ${?0} ) then
		# FINISHED: special handler for when this file is sourced.
		if( -d "${scripts_path}/../tcshrc" && -f "${scripts_path}/../tcshrc/argv:clean-up" ) \
			source "${scripts_path}/argv:clean-up" "${scripts_basename}";
		# END: source support
	endif
	
	if( ${?touch_targets} ) then
		if( -e "${touch_targets}" ) \
			rm -f "${touch_targets}";
		unset touch_targets;
	endif
	
	if( ${?supports_being_source} ) \
		unset supports_being_source;
	if( ${?scripts_basename} ) \
		unset scripts_basename;
	if( ${?scripts_path} ) \
		unset scripts_path;
	if( ${?script} ) \
		unset script;
	if( ${?scripts_exec} ) \
		unset scripts_exec;
	if( ${?chmod_exec} ) \
		unset chmod_exec;
	if( ${?escaped_cwd} ) \
		unset escaped_cwd;
	if( ${?dependency} ) \
		unset dependency;
	if( ${?dependencies} ) \
		unset dependencies;
	if( ${?debug} ) \
		unset debug;
	if( ${?touch_target} ) \
		unset touch_target;
	if( ${?usage_displayed} ) \
		unset usage_displayed;
	if( ${?exit_on_usage} ) \
		unset exit_on_usage;
	if( ${?use_old_owd} ) then
		cd "${owd}";
		set owd="${use_old_owd}";
		unset use_old_owd;
	endif
	exit ${status}
#goto scripts_main_quit;


missing_dependency:
	printf "One or more required dependencies couldn't be found.\n\n[%s] couldn't be found.\n\n%s requires: %s" "${dependency}" "${scripts_basename}" "${dependencies}";
	set status=-1;
	goto exit_script;
#goto missing_dependency;


usage:
	if(! ${?usage_displayed} ) then
		printf "\n\n\tUsage: %s FILE\n\tor: %s MODE FILE\n\tUpdate the access and modification times of each FILE to the current time.\n\tA FILE argument that does not exist is created empty as are any missing parent directories.\n\n" "${scripts_basename}" "${scripts_basename}";
	endif
	
	if(! ${?usage_displayed} ) \
		set usage_displayed;
	if( ${?exit_on_usage} ) \
		goto exit_script;
	
	goto parse_arg;
#goto usage;


parse_argv:
	@ argc=${#argv};
	@ arg=0;
	@ parsed_argc=0;
	if( ${?debug} || ${?diagnostic_mode} ) \
		printf "**%s debug:** checking argv.  %d total arguments.\n\n" "${scripts_basename}" "${argc}";
	set argz;
#goto parse_argv;

parse_arg:
	while( $arg < $argc )
		if( ! ${?arg_shifted} || ${?value_used} ) \
			@ arg++;
		
		set argument_file="${scripts_tmpdir}/.escaped.argument.${scripts_basename}.argv[${arg}].`date '+%s'`.arg";
		printf "%s" "$argv[${arg}]" >! "${argument_file}";
		ex -s '+s/\v([\"\!\$\`])/\"\\\1\"/g' '+wq!' "${argument_file}";
		set escaped_argument="`cat "\""${argument_file}"\""`";
		rm -f "${argument_file}";
		unset argument_file;
		set argument="`printf "\""%s"\"" "\""${escaped_argument}"\""`";
		
		set dashes="`printf "\""%s"\"" "\""${escaped_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\1/'`";
		if( "${dashes}" == "${argument}" ) \
			set dashes="";
		
		set option="`printf "\""%s"\"" "\""${escaped_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\2/'`";
		if( "${option}" == "${argument}" ) \
			set option="";
		
		set equals="`printf "\""%s"\"" "\""${escaped_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\3/'`";
		if( "${equals}" == "${argument}" ) \
			set equals="";
		
		set value="`printf "\""%s"\"" "\""${escaped_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\4/'`";
		
		if( ${?debug} ) \
			printf "\tparsed "\$"argument: [%s]; "\$"argv[%d] (%s)\n\t\t"\$"dashes: [%s];\n\t\t"\$"option: [%s];\n\t\t"\$"equals: [%s];\n\t\t"\$"value: [%s]\n\n" "${argument}" "${arg}" "$argv[${arg}]" "${dashes}" "${option}" "${equals}" "${value}" > ${stdout};
		
		if( "${dashes}" != "" && "${option}" != "" && "${equals}" == "" && "${value}" == "" ) then
			@ arg++;
			if( ${arg} > ${argc} ) then
				@ arg--;
			else
				if( ${?debug} ) \
					printf "**%s debug:** Looking for replacement value.  Checking argv #%d (%s).\n" "${scripts_basename}" ${arg} "$argv[${arg}]" > ${stdout};
				
				set argument_file="${scripts_tmpdir}/.escaped.argument.${scripts_basename}.argv[${arg}].`date '+%s'`.arg";
				printf "%s" "$argv[${arg}]" >! "${argument_file}";
				ex -s '+s/\v([\"\!\$\`])/\"\\\1\"/g' '+wq!' "${argument_file}";
				set escaped_test_argument="`cat "\""${argument_file}"\""`";
				rm -f "${argument_file}";
				unset argument_file;
				set test_argument="`printf "\""%s"\"" "\""${escaped_test_argument}"\""`";
				
				set test_dashes="`printf "\""%s"\"" "\""${escaped_test_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\1/'`";
				if( "${test_dashes}" == "${test_argument}" ) \
					set test_dashes="";
				
				set test_option="`printf "\""%s"\"" "\""${escaped_test_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\2/'`";
				if( "${test_option}" == "${test_argument}" ) \
					set test_option="";
				
				set test_equals="`printf "\""%s"\"" "\""${escaped_test_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\3/'`";
				if( "${test_equals}" == "${test_argument}" ) \
					set test_equals="";
				
				set test_value="`printf "\""%s"\"" "\""${escaped_test_argument}"\"" | sed -r 's/^([\-]{1,2})([^\=]+)(\=)?(.*)"\$"/\4/'`";
				
				if( ${?debug} ) \
					printf "\t\tparsed argument for possible replacement value:\n\t\t\t"\$"test_argument: [%s]; "\$"argv[%d] (%s)\n\t\t\t"\$"test_dashes: [%s];\n\t\t\t"\$"test_option: [%s];\n\t\t\t"\$"test_equals: [%s];\n\t\t\t"\$"test_value: [%s]\n\n" "${test_argument}" "${arg}" "$argv[${arg}]" "${test_dashes}" "${test_option}" "${test_equals}" "${test_value}" > ${stdout};
				if(!( "${test_dashes}" == "" && "${test_option}" == "" && "${test_equals}" == "" && "${test_value}" == "${test_argument}" )) then
					@ arg--;
				else
					set equals=" ";
					set value="${test_value}";
					set arg_shifted;
				endif
				unset escaped_test_argument test_argument test_dashes test_option test_equals test_value;
			endif
		endif
		
		if( "${value}" != "" ) then
			set value_file="${scripts_tmpdir}/.escaped.argument.${scripts_basename}.argv[${arg}].`date '+%s'`.arg";
			printf "%s" "${value}" >! "${value_file}";
			ex -s '+s/\v([\"\!\$\`])/\"\\\1\"/g' '+wq!' "${value_file}";
			set escaped_value="`cat "\""${value_file}"\""`";
			rm -f "${value_file}";
			unset value_file;
			set value="`printf "\""%s"\"" "\""${escaped_value}"\""`";
		endif
		
		@ parsed_argc++;
		set parsed_arg="${dashes}${option}${equals}${value}";
		if(! ${?parsed_argv} ) then
			set parsed_argv="${parsed_arg}";
		else
			set parsed_argv="${parsed_argv} ${parsed_arg}";
		endif
		
		if( ${?debug} || ${?diagnostic_mode} ) \
			printf "\tparsed option %sparsed_argv[%d]: %s\n" \$ "$parsed_argc" "${parsed_arg}";
		
		switch("${option}")
			case "h":
			case "help":
				if(! ${?exit_on_usage} ) \
					set exit_on_usage;
				goto usage;
				breaksw;
			
			case "diagnosis":
			case "diagnostic-mode":
			case "debug":
				breaksw;
			
			case "v":
			case "verbose":
				set be_verbose;
				breaksw;

			case "a":
			case "c":
			case "d":
			case "date":
			case "f":
			case "help":
			case "m":
			case "no-create":
			case "r":
			case "reference":
			case "t":
			case "time":
			case "version":
				if( ${dashes} != "" ) then
					set argz="${argz} $argv[$arg]";
				else
					set argz="${argz}$argv[$arg]";
				endif
				breaksw;
			
			case "":
				if( ! ${?mode} && "${value}" != "" && "`printf "\""%s"\"" "\""${escaped_value}"\"" | sed -r 's/[ugo]{0,3}[\+\-=][rwxXst]{1,6}//'`" == "" ) then
					set mode="${value}";
					if( ${?debug} ) \
						printf "All files touched will also have their priviledges changed to: %s.\n" "${mode}";
					breaksw;
				endif
				
				if(! ${?touch_targets} ) \
					set touch_targets="`mktemp --tmpdir .escaped.${scripts_basename}.targets.XXXXXXXXXX`";
				if( ${?debug} ) \
					printf "Adding %s to <file://%s>\n" "${value}" "${touch_targets}";
				printf "${value}\n" >> "${touch_targets}";
				breaksw;
			
			default:
				printf "%s%s%s%s is an unsupported option.  See %s -h|--help for more information.\n" "${dashes}" "${option}" "${equals}" "${value}" "${scripts_basename}" >& ${stderr};
				breaksw;
		endsw
		
		unset dashes option equals value parsed_arg;
		
		if( ${?arg_shifted} ) then
			if(! ${?value_used} ) \
				@ arg--;
			unset arg_shifted;
		endif
	end
	goto exec;
#goto parse_arg;


