#!/bin/tcsh -f
if( ! ( ${?1} && "${1}" != "" && -e "${1}" ) ) then
	printf "Usage: %s filename to revese.\n" "`basename '${0}'`";
	exit -1;
endif

if(! ${?1} ) setenv eol '$';

set revesed_filename="`printf "\""${1}"\"" | sed 's/\(.*\)\([^\.]\+\)\.\(.*\)${eol}/\1\2\.reversed\.\3/'`";

set lines="`wc -l '${1}' | sed 's/^\([0-9]\+\).*${eol}/\1/'`";

if( ${lines} >= 1000 ) then
	@ place=3;
else if( ${lines} >= 100 ) then
	@ place=2;
else
	@ place=1;
endif

cat --number "${1}" | sed 's/^[\ \t]\+//' | sed "s/^\([1-9]\{${place}\}\)\([\ \t]\)/0\1\2/" | sort -r | sed 's/^[0-9]\+[\ \t]\+//' >! "${revesed_filename}";
