#!/bin/tcsh -f
set program="/programs/Mozilla/Firefox3/x86_64/firefox-bin";

if ( !( ${?program} && -x "${program}" ) ) then
	printf "Unable to find %s.\n", "${this_program}";
	exit -1;
endif

if ( !( ${?program} && -x "${program}" ) ) then
	printf "Unable to find %s.\n", "${this_program}";
	exit -1;
endif

echo "${program} ${argv}";


if( ! ${?OUTPUT_STDERR} ) then
	( ${program} ${argv} > /dev/tty ) >& /dev/null &
else
	${program} ${argv} >& /dev/null &
endif

unset this_program;

