#!/bin/tcsh -f
set program="/programs/Mozilla/Firefox3/x86_64/firefox-bin";

if(! ${?program} ) goto noexec;
if(! -x "${program}" ) goto noexec;
goto launchers_main;

noexec:
	printf "Unable to find %s.\n", "${this_program}";
	if( ${?program} ) unset program;
	unset this_program;
	exit -1;

launchers_main:

echo "${program} ${argv}";


if( ! ${?OUTPUT_STDERR} ) then
	( ${program} ${argv} > /dev/tty ) >& /dev/null &
else
	${program} ${argv} >& /dev/null &
endif

unset this_program;

