#!/bin/tcsh -f
set this_program="`basename '${0}'`";

while( ${?1} && "${1}" != "" && ! ${?program_path} )
	switch( "${1}" )
	case "--launch-in-terminal":
	case "--use-launcher":
	case "--launcher":
		shift;
		set use_launcher;
		breaksw
	case "--3.5":
		shift;
		set program_path="/usr/bin";
		breaksw
	case "--nightly-build":
	default:
		set rm_extensions;
		set program_path="/programs/Mozilla/Firefox3/x86_64";
		breaksw
	endsw
end

if(!(${?program_path})) set program_path="/programs/Mozilla/Firefox3/x86_64";

ff_init:
set firefox_profile_path="/profile.d/~slash./mozilla/${this_program}/profiles";
set program="${program_path}/${this_program}";
if( !( ${?program} && -x "${program}" ) ) then
	printf "Unable to find %s.\n", "${this_program}";
	exit -1;
endif
if(( (${?1} && "${1}" == "-P") && (${?2} && "${2}" != "" && -d "${firefox_profile_path}/${2}") )) then
	set argz="${1} ${2}";
	shift;
	shift;
else
	set argz="-P uberChick";
endif

set ff_binaries=("${this_program}-bin", "${this_program}");

@ ff_attempt=0;
ff_check:
foreach ff_binary( ${ff_binaries} )
	foreach firefox_pid("`pidof -x ${ff_binary} | sed 's/\ /\n/g'`")
		if( $firefox_pid > 0 ) then
			renice +10 $firefox_pid >& /dev/null;
			if(! ${?ff_found} ) set ff_found;
		endif
	end
end
if(! ${?ff_found} ) then
	@ ff_attempt++;
	if( ${ff_attempt} == 1 ) goto ff_start
else
	@ ff_attempt=6;
	goto ff_start;
endif
if( ${?rm_extensions} ) rm ${firefox_profile_path}/${2}/extensions.* >& /dev/null &;
sleep 5;

goto ff_start;

exit;

ff_start:
if( ${?use_launcher} ) then
	#echo /usr/bin/gnome-terminal --role="launcher:${this_program}" --geometry=80x10 --hide-menubar --tab-with-profile='/bin/tcsh -f' --command="${program} ${argv}" \>\& /dev/null \&;
	/usr/bin/gnome-terminal --role="launcher:${this_program}" --geometry=80x10 --hide-menubar --tab-with-profile='/bin/tcsh -f' --command="${program} ${argz} ${argv}" >& /dev/null &;
else
	#echo ${program} "${argv}";
	${program} "${argz}" "${argv}";
endif
if( ${ff_attempt} > 5 ) then
	if(! ${?ff_found} ) then
		set status=-1;
	else
		set status=0;
	endif
	unset this_program ff_binaries ff_binary;
	exit ${status};
endif

sleep 2;

goto ff_check;

