#!/bin/tcsh -f
set browser="links"
while( ${?1} && "${1}" != "" )
	switch("${1}")
		case "--firefox":
			set browser="firefox";
			shift
			breaksw
		default:
			if( ${?search_phrase} ) then
				set search_phrase="${search_phrase} ${1}";
			else
				set search_phrase="${1}";
			endif
			shift
			breaksw
	endsw
end

${browser} "http://google.com/search?q=${search_phrase}"

