#!/bin/tcsh -f
if(! ${?0} ) then
	printf "This script does not support being sourced.\n";
	exit -1;
endif

set this_program="`basename '${0}'`";
foreach program ( "`which '${this_program}'`" )
	if( "${program}" != "${0}" && -x "${program}" ) \
		break;
	unset program;
end

if(! ${?program} ) \
	goto noexec;
if(! -x "${program}" ) \
	goto noexec;
goto launchers_main;

noexec:
	printf "Unable to find %s.\n" "${this_program}";
	if( ${?program} ) \
		unset program;
	unset this_program;
	exit -1;

launchers_main:

if( ! ${?OUTPUT_STDERR} ) then
	( ${program} ${argv} > /dev/tty ) >& /dev/null
else
	${program} ${argv} >& /dev/null
endif

unset this_program;

