#!/bin/tcsh -f
set this_program="`basename '${0}'`";

foreach program ( "`which '${this_program}'`" )
	if( -x "${program}" ) end
endif

if ( !( ${?program} && -x "${program}" ) ) then
	printf "Unable to find %s.\n", "${this_program}";
	exit -1;
endif

if( ${1} < 0 ) set program="sudo ${program}";

if( ! ${?OUTPUT_STDERR} ) then
	( ${program} ${argv} > /dev/tty ) >& /dev/null
else
	${program} ${argv} >& /dev/null
endif

unset this_program;

