#!/bin/tcsh -f
if(! ${?TCSH_LAUNCHER_PATH} ) \
	setenv TCSH_LAUNCHER_PATH \$"{TCSH_RC_SESSION_PATH}/../launchers";


set this_program="renice";

foreach program ( "`which "\""${this_program"\""'`" )
	if( "${program}" != "${0}" && -x "${program}" ) \
		break;
	unset program;
end

if(! ${?program} ) \
	goto noexec;
if(! -x "${program}" ) \
	goto noexec;

if(! ${?0} ) then
	alias "${this_program}"	\$"{TCSH_LAUNCHER_PATH}/${this_program}";
	complete ${this_program} 'p/1/(-19 -18 -17 -16 -15 -14 -13 -12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 +1 +2 +3 +4 +5 +6 +7 +8 +9 +10 +11 +12 +13 +14 +15 +16 +17 +18 +19 +20)/' 'p/2-/c/'
	goto main_quit;
endif

goto launchers_main;

noexec:
	printf "Unable to find %s.\n" "${this_program}";
	goto main_quit;
noexec:

main_quit:
	unset dependencies;
	unset this_program;
	if( ${?dependency} ) \
		unset dependency;
	if( ${?program} ) \
		unset program;
	if( ${?this_program} ) \
		unset this_program;
	exit ${status};
#main_quit

usage:
	printf "%s priority pid" "${this_program}";
	goto main_quit;
#usage:

launchers_main:
	while( "${1}" != "" )
		if( "${1}" == "--help" || "${1}" == "-h" ) then
			goto usage;
		else if(! ${?priority} ) then
			if( `printf "${1}" | sed -r 's/^[\+\-]?[0-9]+$//'` == "" ) \
				set priority="${1}";
		else if(! ${?pid} ) then
			if( `printf "${1}" | sed -r 's/^[0-9]+$//'` == "" ) \
				set pid="${1}";
		endif
		
		shift;
	end
	
	if(!( ${?priority} && ${?pid} )) \
		goto usage;
	
	if( $uid != 0 && `printf "${priority}" | sed -r 's/^(.).*$/\1/'` == "-" ) \
		set program="sudo ${program}";
	
	echo ${program} ${priority} ${pid};
	${program} ${priority} ${pid};

	unset this_program program;
	goto main_quit;
#goto launchers_main;

