#!/bin/tcsh -f
set screens_command="/usr/bin/screen -aAUR";
set screens_sessions=`/usr/bin/screen -list`;
if( "$screens_sessions[1]" != "No" ) set screens_command="${screens_command}x";
unset screens_sessions;

$screens_command
