#!/bin/tcsh -f
if( "`echo '${0}' | sed -r 's/^[^\.]*(tcsh)/\1/'`" == "tcsh" ) exit;
set this_program="`basename '${0}'`";

foreach program ( "`which '${this_program}'`" )
	if( "${program}" != "${0}" && -x "${program}" ) break;
	unset program;
endif

if(! ${?program} ) goto noexec;
if(! -x "${program}" ) goto noexec;
goto launchers_main;

noexec:
	printf "Unable to find %s.\n" "${this_program}";
	if( ${?program} ) unset program;
	unset this_program;
	exit -1;

launchers_main:

unset this_program;
if( ! ${?OUTPUT_STDERR} ) then
	( ${program} ${argv} > /dev/tty ) >& /dev/null &
else
	${program} ${argv} >& /dev/null &
endif

unset program;
