#!/bin/tcsh -f
if( "`echo '${0}' | sed -r 's/^[^\.]*(tcsh)/\1/'`" == "tcsh" ) exit;
if(! ${?TCSH_LAUNCHER_PATH} ) setenv TCSH_LAUNCHER_PATH "${TCSH_RC_SESSION_PATH}/../launchers";

set dependencies=( "`basename '${0}'`" );

foreach dependency(${dependencies})
	foreach dependency( "`where '${dependency}'`" )
		if(! -x "${dependency}" ) then
			unset dependency;
		else
			switch("${dependency}")
				case "${0}":
				case "./${dependency}":
				case "${TCSH_LAUNCHER_PATH}/${dependency}":
					unset dependency;
					breaksw;
			endsw
		endif
	end
	if(! ${?dependency} ) goto missing_dependency;
end

set program="${dependency}";
goto parse_argv;

main:
	set status=0;
	( ${program} ${argz} > /dev/tty ) >& /dev/null;

main_quit:
	unset dependencies;
	if( ${?dependency} ) unset dependency;
	if( ${?program} ) unset program;
	exit ${status};
#main_quit

missing_dependency:
	printf "Unable to find %s.\n" "${dependency}";
	set status=-1;
	goto main_quit;

parse_argv:
	set argz="";
	while ( "${1}" != "" )
		set option="`printf "\""${1}"\"" | sed -r 's/[\-]{1,2}([^=]+)=?['\''"\""]?(.*)['\''"\""]?/\1/'`";
		set value="`printf "\""${1}"\"" | sed -r 's/[\-]{1,2}([^=]+)=?['\''"\""]?(.*)['\''"\""]?/\2/'`";
		switch("${option}")
			default:
				set argz="${1}";
				breaksw
		endsw
		shift;
	end
	unset option value;
	goto main;

