#!/bin/tcsh -f
set this_program="`basename '${0}'`";

foreach program ( "`which '${this_program}'`" )
	if( -x "${program}" ) end
endif

if( !( ${?program} && -x "${program}" ) ) then
	printf "Unable to find %s.\n", "${this_program}";
	exit -1;
endif

( ${program} ${argv} > /dev/tty ) >& /dev/null &

