#!/bin/tcsh -f
while( ${?1} && "${1}" != "" )
	switch("${1}")
		case "--firefox":
		case "--links":
		case "--lynx":
			set browser="`echo -n '${1}' | sed -r 's/[\-]{2}(.*)/\1/'`";
			shift;
			breaksw
		default:
			if( ! ${?browser} && "`echo -n '${1}' | sed -r 's/[\-]{2}(browser)=(.*)/\1/'`" == "browser" ) then
				set exec_test="`echo -n '${1}' | sed -r 's/[\-]{2}browser=(.*)/\1/'`";
				foreach browser("`where '${exec_test}'`")
					if( ${?exec_test} ) unset exec_test;
					if( -x "${browser}" ) then
						shift;
						breaksw
					endif
				end
				if( ${?browser} ) unset browser;
			endif
			
			if( ${?url_to_shorten} ) then
				set url_to_shorten="${url_to_shorten} ${1}";
			else
				set url_to_shorten="${1}";
			endif
			shift;
			breaksw
	endsw
end

if(! ${?browser} ) then
	if( "${TERM}" == "gnome" ) then
		set browser="firefox";
	else
		set browser="wget"
	endif
endif

if( -x "${browser}" ) then
	set program="${browser}";
else
	foreach program ( "`which '${browser}'`" )
		if( "${program}" != "${0}" && -x "${program}" ) break
	end
endif

if(! ${?program} ) goto noexec;
if(! -x "${program}" ) goto noexec;
goto launchers_main;

noexec:
	printf "Unable to find %s.\n" "${browser}";
	if( ${?program} ) unset program;
	unset browser;
	exit -1;

launchers_main:

set url_shortener_domain="kissa\.be";
set url_shortener_uri="http://kissa.be/shortener/set?status=url&content_data=${url_to_shorten}";
if(! ${?eol} ) setenv eol='$';
switch ( "${browser}" )
	case "wget":
		set short_url_html="./.url-shortener.`date '+%s'`.log";
		${program} -q -O "${short_url_html}" "${url_shortener_uri}";
		/bin/grep --perl-regexp "${url_shortener_domain}" "${short_url_html}" | /bin/sed -r "s/.*"\"".*(${url_shortener_domain})\/.*\/([^\/"\""]+)"\""\ \/>${eol}/http:\/\/\1\/\2/";
		rm "${short_url_html}";
		breaksw
	default:
		${program} "${url_shortener_uri}";
		breaksw
endsw
