#!/bin/tcsh -f
if( ! ${?this_program} ) set this_program="xfmedia";
foreach program ( "`where '${this_program}'`" )
	if( "${program}" != "${0}"  && "${program}" != "./${this_program}" && "${program}" != "${launchers_path}/${this_program}" && -x "${program}" ) break
end

if( !( ${?program} && -x "${program}" ) ) then
	printf "Unable to find %s.\n" "${this_program}";
	exit -1;
endif

if( ! ${?audio_driver} ) set audio_driver="esd";

if( ! ${?video_driver} ) set video_driver="fb";

if( ! ${?resolution} ) set resolution=`cat "/projects/cli/resolutions/video/hd.rc"`;

if( ! ${?output} ) set output=">& /dev/null &";

if( "${0}" == "-tcsh" ) then
	set set_alias;
else if( "`basename '${0}'`" != "${program}" ) then
	set set_alias;
endif

if( ${?set_alias} ) then
	if( ! ${?alias_suffix} ) then
		set new_alias="${this_program}";
	else
		set new_alias="${this_program}-${alias_suffix}";
	endif
	if( ${?TCSHRC_DEBUG} ) printf "Aliasing [%s] to [%s].\n" $new_alias $program;
	#alias "${new_alias}" "${program} --video-out='${video_driver}' --audio-out='${audio_driver}' --vwin-geometry='${resolution}' ${argv} ${output}";
	alias "${new_alias}" "${program} --audio-out='${audio_driver}' --vwin-geometry='${resolution}' ${argv} ${output}";
else
	${program} --video-out="${video_driver}" --audio-out="${audio_driver}" --vwin-geometry="${resolution}" ${argv} ${output};
endif

unset this_program;

