#!/bin/tcsh -f
if( ! ${?this_program} ) set this_program="xfmedia";
foreach program ( "`which '${this_program}'`" )
	if( -x "${program}" ) end
endif

if ( !( ${?program} && -x "${program}" ) ) then
	printf "Unable to find %s.\n", "${this_program}";
	exit -1;
endif

if( ! ${?audio_driver} ) set audio_driver="esd";

if( ! ${?video_driver} ) set video_driver="opengl";

if( ! ${?resolution} ) set resolution=`cat "/projects/cli/resolutions/video/hd.rc"`;

if( ! ${?settings} ) set settings="${HOME}/.config/${program}/settings.xml";
#if( ! ${?condition} ) set condition="if ( -e '${settings}' ) mv '${settings}' '${settings}.bck'; ";
if ( ! ${?condition} ) set condition="";
if( ! ${?output} ) set output=">& /dev/null &";

if( "${0}" == "-tcsh" ) then
	set set_alias;
else if( "`basename '${0}'`" != "${program}" ) then
	set set_alias;
endif

if( ${?set_alias} ) then
	if ( ! ${?alias_suffix} ) then
		set new_alias="${this_program}";
	else
		set new_alias="${this_program}-${alias_suffix}";
	endif
	if( ${?TCSHRC_DEBUG} ) printf "Aliasing [%s] to [%s/%s].\n" $new_alias $program;
	alias "${new_alias}" "${condition}${program} --video-out='${video_driver}' --audio-out='${audio_driver}' --vwin-geometry='${resolution}' ${argv} ${output}";
else
	${this_program};
	#${condition}${this_program} --video-out="${video_driver}" --audio-out="${audio_driver}" --vwin-geometry="${resolution}" ${argv} ${output};
endif

unset this_program;

