#!/bin/tcsh -f
set launcher="xine";

source "${launchers_path}/${launcher}";

foreach resolution_source ( /projects/cli/resolutions/video/* )
	set alias_suffix=`basename "${resolution_source}" | cut -d'.' -f1`;
	set resolution=`cat "${resolution_source}"`;
	if( ${?TCSHRC_DEBUG} ) printf "Sourcing: %s\n" $launcher;
	source "${launchers_path}/${launcher}";
end


unset audio_driver video_driver resolution resolution_source alias_suffix program;

