#!/bin/tcsh -f
if(! ${?0} ) then
	printf "This script cannot be sourced.\n";
	exit -1;
endif

set this_program="`basename '${0}'`";

foreach program ( "`which '${this_program}'`" )
	if( "${program}" != "${0}" && -x "${program}" ) \
		break;
	unset program;
end

if(! ${?program} ) \
	goto noexec;
if(! -x "${program}" ) \
	goto noexec;
goto launchers_main;

noexec:
	printf "Unable to find %s.\n", "${this_program}";
	exit -1;

launchers_main:

if( ${?GREP_OPTIONS} ) then
	set grep_options="${GREP_OPTIONS}";
	unsetenv GREP_OPTIONS;
endif

set my_args="";
set prefix="";
set suffix="";
while( ${?1} && "${1}" != "" )
	switch( "${1}" )
	case "install":
		set suffix=" --no-recommends";
		breaksw
	case "search":
	case "info":
		set prefix="--no-refresh ";
		#set suffix=" --search-descriptions --details";
		set suffix=" --details";
		breaksw
	endsw
	
	set my_args="${my_args} ${prefix}${1}${suffix}";
	if( "${prefix}" != "" ) \
		set prefix="";
	if( "${suffix}" != "" ) \
		set suffix="";
	shift;
end

if(${uid} != 0) then
	exec sudo ${program} ${my_args} ${argv};
else
	exec ${program} ${my_args} ${argv};
endif


if( ${?grep_options} ) then
	setenv GREP_OPTIONS "${grep_options}";
	unset grep_options;
endif

unset suffix prefix my_args;
