#!/bin/tcsh -f
if(! ${?0} ) then
	printf "This script can, not sourced, only be executed.\n" > /dev/stderr;
	set status=-1;
	exit ${status};
endif

set scripts_basename=`basename "\""${0}"\""`;
@ argc=${#argv};

if(!( ${argc} > 2 )) then
	printf "Usage:\n\t%s [perl regex search term] [search file match or directory]\nExamples:\n\t%s 'find_uniq\([^\(]+char \*phrase[^\(]*\)' src/*.[ch]\n" "${scripts_basename}" "${scripts_basename}";
	set status=-1;
	exit ${status};
endif

onintr exit_script;

set regexp="$argv[1]";
@ arg=1;
while( $arg < $argc )
	@ arg++;
	if(! -e "$argv[$arg]" ) then
		printf "I can't grep what I can't find.  Where is it?  <file://%s>:\t[skipped]\n" > /dev/stderr;
		continue;
	endif
	
	( /bin/grep --binary-files=without-match --color --with-filename --line-number --no-messages --perl-regexp \
		"${regexp}" "$argv[$arg]"  | sed -r 's/^(.*):[0-9]:.*$/\1/' > "${filelist}" ) >& /dev/null;
end

exit_script:
	if( ${?filelist} ) then
		if( -e "${filelist}" ) then
			cat "${filelist}" | sort | uniq;
			rm -f "${filelist}";
		endif
		unset filelist;
	endif
#goto exit_script;
