#!/bin/tcsh -f
if(!( ${?1} && "${1}" != "" && -d "${1}")) then
	set prefix="/usr";
else
	set prefix="${1}";
endif

./configure --libdir=/usr/lib64 --prefix="${prefix}";
if( "${status}" != "0" ) exit ${status};

make
if( "${status}" != "0" ) exit ${status};

sudo make install
if( "${status}" != "0" ) exit ${status};

make distclean
if( "${status}" != "0" ) exit ${status};

git:commit+push+sync

set exec_bin=`pwd`;
${prefix}/bin/`basename ${exec_bin}` >& /dev/null &

