#!/bin/tcsh -f
if(! ${?0} ) then
	printf "This script cannot be sourced.";
	@ status=-1;
	exit ${status};
endif

set resolutions_path="`dirname '${0}'`/../resolutions/gnome-terminal";

set ericas_dimensions=`cat "${resolutions_path}/erica.rc"`;
set artistic_geometry=`cat "${resolutions_path}/artistic.rc"`;
set media_geometry=`cat "${resolutions_path}/media.rc"`;
set canvas_geometry=`cat "${resolutions_path}/canvas.rc"`;
set editor_geometry=`cat "${resolutions_path}/editor.rc"`;
set alacast_geometry=`cat "${resolutions_path}/alacast.rc"`;
set default_geometry=`cat "${resolutions_path}/default.rc"`;
set build_geometry=`cat "${resolutions_path}/build.rc"`;
set ssh_geometry=`cat "${resolutions_path}/ssh/default.rc"`;

set screens_command="`dirname '${0}'`/../launchers/screen";

if(! ${?noglob} ) \
	set noglob;

foreach canvas ( "${argv}" )
	
	set my_gnome_terminal="/usr/bin/gnome-terminal --hide-menubar --role='${canvas}'";
	set canvas_role="${canvas}";
	set canvas_type="`printf "\""%s"\"" "\""${canvas}'"\""| sed 's/^\([^:]\+\):\(.*\)/\L\1/g'`";
	set canvas="`printf "\""%s"\"" "\""${canvas}"\"" | sed 's/^\([^:]\+\):\(.*\)/\L\2/g'`";
	
	switch( "${canvas_type}" )
	case "editor":
		shift;
		set geometry="${editor_geometry}";
		goto editor_canvas;
		breaksw;
	
	case "canvas":
		shift;
		set geometry="${canvas_geometry}";
		goto canvas_canvas;
		breaksw;
	
	case "artistic":
		shift;
		set geometry="${artistic_geometry}";
		goto artistic_canvas;
		breaksw;
	
	case "media":
		shift;
		set geometry="${media_geometry}";
		goto media_canvas;
		breaksw;
	
	case "build":
		shift;
		set geometry="${build_geometry}";
		goto build_canvas;
		breaksw;
	
	case "ssh":
		set geometry="${ssh_geometry}";
		goto ssh_canvas;
		breaksw;
	
	case "erica":
		set geometry="${ericas_dimensions}";
		goto erica_design_canvas;
		breaksw;
	
	case "default":
	default:
		set geometry="${default_geometry}"
		goto default_canvas;
		breaksw;
	endsw

	goto next_canvas;
##:


erica_design_canvas:
	set with_screen;
	set with_ssh_our_eee;
	switch( "${canvas}" )
		case "resources":
			set my_canvas=( \
				"--tab-with-profile=./erica --title='[@./erica] #>' --working-directory=/art/erica" \
				"--tab-with-profile=project:art --title='[@/art] #>' --working-directory=/art" \
				"--tab-with-profile=project:art --title='[@/art/media] #>' --working-directory=/art/media" \
				"--tab-with-profile=project:art --title='[@/media-library] #>' --working-directory=/media/library" \
			);
			breaksw;
		
		case "tools":
			set my_canvas= ( \
				"--tab-with-profile=opensim --title='[./e->(`opensim`);] #>' --working-directory='/art/erica/tools/servers/opensim/bin --command=/art/erica/tools/servers/opensim/OpenSim.tcsh'" \
				"--tab-with-profile=./erica --title='[./e->(erica:engines);] #>' --working-directory=/art/erica/libraries-and-engines" \
				"--tab-with-profile=./erica --title='[./e->(tools);] #>' --working-directory=/art/erica/tools" \
			);
			breaksw;
		
		case "all":
		case "allpieces":
		case "pieces":
			set my_canvas=( \
				"--tab-with-profile=./erica --title='[@./erica] #>' --working-directory=/art/erica" \
				"--tab-with-profile=./erica --title='[./e->(our-many-worlds);] #>' --working-directory=/art/erica/my_pieces/our-many-worlds" \
				"--tab-with-profile=./erica --title='[./e->(hackGirls);] #>' --working-directory=/art/erica/my_pieces/hackGirls" \
				"--tab-with-profile=./erica --title='[./e->(alacast);] #>' --working-directory=/art/erica/my_pieces/alacast" \
			);
			breaksw;
		
		case "erica":
		case "design":
		default:
			set my_canvas=( \
				"--tab-with-profile=./erica --title='[@./erica] #>' --working-directory=/art/erica" \
				"--tab-with-profile=art --title='[@/art] #>' --working-directory=/art" \
				"--tab-with-profile=projects --title='[@/projects] #>' --working-directory=/projects" \
				"--tab-with-profile=art:media --title='[@/media] #>'  --working-directory=/media" \
				"--tab-with-profile=./erica --title='[./e->(alacast);] #>' --working-directory=/art/erica/my_pieces/alacast" \
				"--tab-with-profile=build:canvas --title='[@build:canvas] #>' --working-directory=/programs/src" \
				"--tab-with-profile=vim-server --title='[`vim-server`;] #>' --working-directory=/media --command=/projects/cli/console.pallet/devel/vim-server" \
			);
			breaksw;
	endsw
	goto next_canvas;
#erica_design_canvas:


artistic_canvas:
	set with_screen;
	set with_ssh_our_eee;
	switch( "${canvas}" )
		case  "GTK":
			set my_canvas=( \
				"--tab-with-profile=projects:gtk --title='[@/gtk] #>' --working-directory=/projects/gtk" \
				"--tab-with-profile=projects:gtk --title='[@connectED] #>' --working-directory=/projects/gtk/connectED" \
				"--tab-with-profile=projects:gtk --title='[@get2gnow] #>' --working-directory=/projects/gtk/get2gnow" \
			);
			breaksw;
		
		case  "CLI":
			set my_canvas=( \
					"--tab-with-profile=projects:cli --title='[@/cli] #>' --working-directory=/projects/cli" \
					"--tab-with-profile=projects:cli --title='[@/profile.d] #>' --working-directory=/profile.d" \
					"--tab-with-profile=projects:cli --title='[@console.pallet] #>' --working-directory=/projects/cli/console.pallet" \
					"--tab-with-profile=projects:cli --title='[@most] #>' --working-directory=/projects/cli/most" \
			);
			breaksw;
	
		case  "WWW":
			set with_ssh_dreams;
			set my_canvas=( \
					"--tab-with-profile=art:www --title='[@/www] #>' --working-directory=/art/www" \
				 	"--tab-with-profile=art:www --title='[@profiles] #>' --working-directory=/art/www/online-profiles" \
					"--tab-with-profile=art:www --title='[@online-oss] #>' --working-directory=/art/www/online-oss" \
					"--tab-with-profile=art:www --title='[@realFriends] #>' --working-directory=/art/www/realFriends" \
					"--tab-with-profile=art:www --title='[@Creative::Code::Canvas] #>' --working-directory=/art/www/Creative::Code::Canvas" \
					"--tab-with-profile=art:www --title='[@a.o.php] #>' --working-directory=/art/www/uberChicGeekChick.Com" \
				);
			breaksw;
		
		case  "MyWebSites":
			set with_ssh_dreams;
			set my_canvas=( \
				"--tab-with-profile=art:www --title='[@uberChicks.Net] #>' --working-directory=/art/www/uberChicks.Net" \
				"--tab-with-profile=art:www --title='[@Dystonia-DREAMS.Org] #>' --working-directory=/art/www/Dystonia-DREAMS.Org" \
				"--tab-with-profile=art:www --title='[@uberChicGeekChick.Com] #>' --working-directory=/art/www/uberChicGeekChick.Com" \
			);
			breaksw;
		
		case  "Projects":
			set my_canvas=( \
				"--tab-with-profile=./erica --title='[./e->(our-many-worlds)] #>' --working-directory=/art/erica/my_pieces/our-many-worlds" \
				"--tab-with-profile=projects:cli --title='[@cli] #>' --working-directory=/projects/cli" \
				"--tab-with-profile=art:www --title='[@a.o.php] #>' --working-directory=/art/www/uberChicGeekChick.Com" \
				"--tab-with-profile=projects:gtk --title='[@get2gnow] #>' --working-directory=/projects/gtk/get2gnow" \
			);
			breaksw;
		
		case  "All":
		default:
			set my_canvas=( \
				"--tab-with-profile=projects:cli --title='[@cli] #>' --working-directory=/projects/cli" \
				"--tab-with-profile=projects:cli --title='[@...console.pallet] #>' --working-directory=/projects/cli/console.pallet" \
				"--tab-with-profile=projects:cli --title='[@...most] #>' --working-directory=/projects/cli/most" \
				"--tab-with-profile=projects:cli --title='[@...alacast.v1] #>' --working-directory=/projects/cli/alacast" \
				"--tab-with-profile=art --title='[@art] #>' --working-directory=/art" \
				"--tab-with-profile=art:www --title='[@www] #>' --working-directory=/art/www" \
				"--tab-with-profile=art:www --title='[@...a.o.php] #>' --working-directory=/art/www/uberChicGeekChick.Com" \
				"--tab-with-profile=projects:gtk --title='[@...gtk] #>' --working-directory=/projects/gtk" \
				"--tab-with-profile=projects:gtk --title='[@...get2gnow] #>' --working-directory=/projects/gtk/get2gnow" \
			);
			breaksw;
	endsw
	goto next_canvas;
#artistic_canvas:


build_canvas:
	switch( "${canvas}" )
		case  "Mozilla":
			set my_canvas=( \
				"--tab-with-profile=uberChick --title='[@mozilla-src] #>' --working-directory=/programs/mozilla/src" \
				"--tab-with-profile=uberChick --title='[@xulrunner-src] #>' --working-directory=/programs/mozilla/src/xulrunner-srcdir" \
				"--tab-with-profile=uberChick --title='[@firefox-src] #>' --working-directory=/programs/mozilla/src/firefox-srcdir" \
				"--tab-with-profile=uberChick --title='[@thunderbird-src] #>' --working-directory=/programs/mozilla/src/thunderbird-srcdir" \
			);
			breaksw;
		
		case  "XULRunner":
			set my_canvas=( \
				"--tab-with-profile=uberChick --title='[@xulrunner-src] #>' --working-directory=/programs/mozilla/src/xulrunner-srcdir" \
			);
			breaksw;

		case  "Canvas":
		default:
			set my_canvas=( \
				"--tab-with-profile=uberChick --title='[@/projects] #>' --working-directory=/projects" \
				"--tab-with-profile=uberChick --title='[@mozilla/src] #>' --working-directory=/programs/mozilla/src" \
				"--tab-with-profile=uberChick --title='[@build:canvas] #>' --working-directory=/programs/src" \
			);
			breaksw;	
	endsw
	goto next_canvas;
#build_canvas:



media_canvas:
	switch ( "${canvas}" )
		case  "Alacast":
			set my_canvas=( \
				"--tab-with-profile=alacast:php --title='[`alacast:php`] #>' --working-directory=/projects/cli/alacast --command=/projects/cli/alacast/bin/alacast.php --mode=update" \
			);
			breaksw;
		case  "Online":
			set with_screen;
			set with_ssh_our_eee;
			set with_ssh_dreams;
			set with_rtorrent;
			
			set my_canvas=( \
				"--tab-with-profile=uberChick --title='[@/projects/media] #>' --working-directory=/projects/media" \
				"--tab-with-profile=uberChick --title='[@/media] #>' --working-directory=/media" \
				"--tab-with-profile=uberChick --title='[@podcasts] #>' --working-directory=/media/podcasts" \
				"--tab-with-profile=project --title='[@alacast.v1] #>' --working-directory=/projects/cli/alacast" \
				"--tab-with-profile=alacast:php --title='[`alacast:php`] #>' --working-directory='/projects/cli/alacast --command=/projects/cli/alacast/bin/alacast.php --mode=update'" \
			);
			breaksw;
	endsw
	goto next_canvas;
#media_canvas:


editor_canvas:
	switch ( "${canvas}" )
		case  "Template":
			set mycanvas=( \
				"--tab --title=~ --working-directory='${HOME}'" \
			);
			breaksw;
		
		case  "VIM":
			set my_canvas=( \
				"--tab-with-profile=uberChick --title='[`vim`] #>' --working-directory=/projects --command='vim-enhanced -p ${argv}'" \
			);
			breaksw;
			
		case  "Default":
		default:
			set my_canvas=( \
				"--tab-with-profile=uberChick --title='["\`"${EDITOR}"\`"] #>' --working-directory=/projects --command='${EDITOR} -p ${argv}'" \
			);
			breaksw;
	endsw
	
	goto next_canvas;
#editor_canvas:


ssh_canvas:
	switch("${canvas}")
		case "EEE":
		case "eee":
			if(! ${?eee_geometry} ) \
				set eee_geometry=`cat "${resolutions_path}/ssh/eee.rc"`;
			set geometry="${eee_geometry}";
			set with_ssh_our_eee;
			set my_canvas=();
			breaksw;
		
		case "dreams":
			set with_ssh_dreams;
			set my_canvas=();
			breaksw;
		
		case "uberchick":
			set with_ssh_uberchick;
			set my_canvas=();
			breaksw;
		
		dofault:
			if( "`printf "\""%s"\"" "\""${canvas}"\"" | sed -r 's/[^@]+(@).*/\1/'`" != "@" ) then
				set server="${USER}@${canvas}";
			else
				set server="${canvas}";
			endif
			
			set my_canvas=( \
				"--tab-with-profile=ssh --title='<ssh:[${server}] #>' --command='ssh -X ${server}'" \
			);
		breaksw;
	endsw
	
	goto next_canvas;
#ssh_canvas:


default_canvas:
	switch ( "${canvas}" )
		case  "Screen":
			set with_screen;
			set with_ssh_our_eee;
			set with_ssh_dreams;
			set my_canvas;
			breaksw;
		
		case "Home":
		case "~":
			set with_home;
			set my_canvas;
			breaksw;
		
		default:
			#set with_screen;
			#set with_ssh_our_eee;
			#set with_ssh_dreams;
			set with_home;
			set my_canvas;
			breaksw;
	endsw
	
	goto next_canvas;
#default_canvas:

next_canvas:
	if( ${?my_canvas} ) then
		if( ( ${?with_screen} || ${?with_rtorrent} ) && ! ${?rtorrent_session_dir} ) then
			if(! -e "${HOME}/.rtorrent.rc" ) then
				set rtorrent_session_dir="${HOME}";
			else
				set rtorrent_session_dir="`/bin/grep 'session' '${HOME}/.rtorrent.rc' | sed -r 's/^[^\=]+\=\ (.*)"\$"/\1/g'`";
				if(!( "${rtorrent_session_dir}" != "" && -d "${rtorrent_session_dir}" )) then
					set rtorrent_session_dir="${HOME}";
				else
					set screens_sessions=`/usr/bin/screen -list`;
					if( "$screens_sessions[1]" == "No" ) then
						rm -f "${rtorrent_session_dir}/rtorrent.lock";
						rm -f "${rtorrent_session_dir}/rtorrent.dht_cache";
					endif
				endif
			endif
		endif
		
		
		if(! ${?with_screen} ) then
			set with_screen;
		else
			set with_screen=("--tab-with-profile=screen --working-directory='${rtorrent_session_dir}'");
		endif
		
		if(! ${?with_ssh_uberchick} ) then
			set with_ssh_uberchick;
		else
			set with_ssh_uberchick=(	\
				"--tab-with-profile=ssh:uberchick" \ \ #--tab-with-profile="\"\\\"\""ssh:uberchick"\"\\\"\"" --title="\"\\\"\""'<ssh:[uberchick@aquarius.ocssolutions.com] #>'"\"\\\"\"" --command="\"\\\"\""ssh -X uberchick@aquarius.ocssolutions.com"\"\\\"\"" \
			);
		endif
		
		if(! ${?with_ssh_dreams} ) then
			set with_ssh_dreams;
		else
			set with_ssh_our_dreams=(	\
				"--tab-with-profile=ssh:dreams" \ \ #--tab-with-profile="\"\\\"\""ssh:dreams"\"\\\"\"" --title="\"\\\"\""'<ssh:[dreams@sky.ocssolutions.com] #>'"\"\\\"\"" --command="\"\\\"\""ssh -X dreams@sky.ocssolutions.com"\"\\\"\"" \
			);
		endif
		
		if(! ${?with_ssh_our_eee} ) then
			set with_ssh_our_eee;
		else
			set with_ssh_our_eee=("--tab-with-profile=ssh:our-eee --title='<ssh:[uberChick@192.168.0.6] #>'");# --command='ssh -X uberChick@192.168.0.6'");
		endif
		
		if(! ${?with_home} ) then
			set with_home;
		else
			set with_home=("--tab-with-profile='${USER}' --title="\'"[@~] #>"\'" --working-directory="\'"${HOME}"\'" --command="\'"tcsh -f"\'"");
		endif
		
		if(! ${?with_rtorrent} ) then
			set with_rtorrent;
		else
			set with_rtorrent=("--tab-with-profile=rtorrent --title='[`rtorrent`] #>' --working-directory=/media/torrents --command='rtorrent'");
		endif
		
		if( "${my_canvas}" != "" ) then
			foreach working_directory("`echo "\""${my_canvas}"\"" | grep 'working-directory'`")
				set canvas_directory="`printf "\""%s"\"" "\""${working_directory}"\"" | sed -r 's/.*\-\-working\-directory\=["\""'\'']?([^\ ]*)["\""'\'']?.*"\$"/\1/'`";
				if( "${canvas_directory}" == "${working_directory}" ) \
					continue;
				
				if( -d "${canvas_directory}" ) \
					continue;
				mkdir -p "${canvas_directory}";
			end
			unset canvas_directory working_directory;
		endif
		
		gnome-terminal --hide-menubar --geometry="${geometry}" --role="${canvas_role}"			\
			${with_screen}										\
			${with_ssh_dreams}									\
			${with_ssh_uberchick}									\
			${with_ssh_our_eee}									\
			${with_home}										\
			${my_canvas}										\
			${with_rtorrent}									\
		&;
		
		unset my_canvas with_screen with_ssh_dreams with_ssh_uberchick with_ssh_our_eee with_home with_rtorrent;
	endif
end

