#!/bin/tcsh -f
if(! ${?eol} ) setenv eol '$';

set resolutions_path="`dirname '${0}'`/../resolutions/gnome-terminal";

set default_geometry=`cat "${resolutions_path}/default.rc"`;
set build_geometry=`cat "${resolutions_path}/build.rc"`;
set games_geometry=`cat "${resolutions_path}/games.rc"`;
set artistic_geometry=`cat "${resolutions_path}/artistic.rc"`;
set media_geometry=`cat "${resolutions_path}/media.rc"`;
set alacast_geometry=`cat "${resolutions_path}/alacast.rc"`;
set canvas_geometry=`cat "${resolutions_path}/canvas.rc"`;
set editor_geometry = `cat "${resolutions_path}/editor.rc"`;

set screens_command="`dirname '${0}'`/../launchers/screen";

foreach canvas ( "${argv}" )
	
	set my_gnome_terminal="/usr/bin/gnome-terminal --hide-menubar --role='${canvas}'";
	set canvas_role="${canvas}";
	set canvas_type="`printf '${canvas}' | sed 's/^\([^:]\+\):\(.*\)/\1/g'`";
	set canvas="`printf '${canvas}' | sed 's/^\([^:]\+\):\(.*\)/\2/g'`";
	
	switch( "${canvas_type}" )
	case "Editor":
		shift;
		set geometry="${editor_geometry}";
		goto editor_canvas
		breaksw;
	
	case "Canvas":
		shift;
		set geometry="${canvas_geometry}";
		goto canvas_canvas
		breaksw;
	
	case "GameDesign":
		shift;
		set geometry="${games_geometry}"
		goto artistic_canvas
		breaksw;
	
	case "Artistic":
		shift;
		set geometry="${artistic_geometry}"
		goto artistic_canvas
		breaksw;
	
	case "Media":
		shift;
		set geometry="${media_geometry}"
		goto media_canvas
		breaksw;
	
	case "Build":
		shift;
		set geometry="${build_geometry}"
		goto build_canvas
		breaksw;
	
	case "Default":
	default:
		set geometry="${default_geometry}"
		goto default_canvas
		breaksw;
	endsw

goto next_canvas


artistic_canvas:
	set with_screen;
	set with_ssh_our_eee;
	switch( "${canvas}" )
		case "GameDesign:MyGames":
			set geometry="${games_geometry}"
			set my_canvas=( \
				"--tab-with-profile=project --title=/projects/games --working-directory=/projects/games" \
				"--tab-with-profile=project --title=many-worlds --working-directory=/projects/games/my-games/many-worlds" \
				"--tab-with-profile=project --title=hackGirls --working-directory=/projects/games/my-games/hackGirls" \
			);
			breaksw;
		
		case "GameDesign:Resources":
			set geometry="${games_geometry}"
			set my_canvas=( \
				"--tab-with-profile=project --title=/media-library --working-directory=/media/library" \
				"--tab-with-profile=project --title=/projects/media --working-directory=/projects/media" \
				"--tab-with-profile=project --title=/art --working-directory=/projects/art" \
				"--tab-with-profile=project --title=/games --working-directory=/projects/games" \
			);
			breaksw;
		
		case "GameDesign:Tools":
			set geometry="${games_geometry}"
			set my_canvas= ( \
				"--tab-with-profile=opensim --working-directory=/projects/games/tools/servers/opensim/bin --command=/projects/games/tools/servers/opensim/OpenSim.tcsh" \
				"--tab-with-profile=projects:games --title=game:engines --working-directory=/projects/games/libraries-and-engines" \
				"--tab-with-profile=projects:games --title=game-design:tools --working-directory=/projects/games/tools" \
			);
			breaksw;
		
		case  "GTK":
			set my_canvas=( \
				"--tab-with-profile=projects:gtk --title=/gtk --working-directory=/projects/gtk" \
				"--tab-with-profile=projects:gtk --title=connectED --working-directory=/projects/gtk/connectED" \
				"--tab-with-profile=projects:gtk --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
				"--tab-with-profile=projects:gtk --title=alacast --working-directory=/projects/gtk/alacast" \
			);
			breaksw;
		
		case  "CLI":
			set my_canvas=( \
					"--tab-with-profile=projects:cli --title=/cli --working-directory=/projects/cli" \
					"--tab-with-profile=projects:cli --title=/profile.d --working-directory=/profile.d" \
					"--tab-with-profile=projects:cli --title=tcshrc --working-directory=/projects/cli/tcshrc" \
			);
			breaksw;
	
		case  "WWW":
			set with_ssh_dreams;
			set my_canvas=( \
					"--tab-with-profile=projects:www --title=/www --working-directory=/projects/www" \
				 	"--tab-with-profile=projects:www --title=profiles --working-directory=/projects/www/online-profiles" \
					"--tab-with-profile=projects:www --title=online-oss --working-directory=/projects/www/online-oss" \
					"--tab-with-profile=projects:www --title=TweetMyBlog --working-directory=/projects/www/TweetMyBlog" \
					"--tab-with-profile=projects:www --title=realFriends --working-directory=/projects/www/realFriends" \
					"--tab-with-profile=projects:www --title=Creative::Code::Canvas --working-directory=/projects/www/Creative::Code::Canvas" \
					"--tab-with-profile=projects:www --title=a.o.php --working-directory=/projects/www/uberChicGeekChick.Com" \
				);
			breaksw;
		
		case  "MyWebSites":
			set with_ssh_dreams;
			set my_canvas=( \
				"--tab-with-profile=projects:www --title=uberChicks.Net --working-directory=/projects/www/uberChicks.Net" \
				"--tab-with-profile=projects:www --title=Dystonia-DREAMS.Org --working-directory=/projects/www/Dystonia-DREAMS.Org" \
				"--tab-with-profile=projects:www --title=uberChicGeekChick.Com --working-directory=/projects/www/uberChicGeekChick.Com" \
			);
			breaksw;
		
		case  "Projects":
			set my_canvas=( \
				"--tab-with-profile=projects:cli --title=console.pallet --working-directory=/projects/cli/console.pallet" \
				"--tab-with-profile=projects:cli --title=alacast-cli --working-directory=/projects/cli/alacast" \
				"--tab-with-profile=projects:www --title=a.o.php --working-directory=/projects/www/uberChicGeekChick.Com" \
				"--tab-with-profile=projects:gtk --title=connectED --working-directory=/projects/gtk/connectED" \
				"--tab-with-profile=projects:gtk --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
				"--tab-with-profile=projects:gtk --title=alacast-gtk --working-directory=/projects/gtk/alacast" \
				"--tab-with-profile=projects:games --title=many-worlds --working-directory=/projects/games/my-games/many-worlds" \
			);
			breaksw;
		
		case  "All":
			set my_canvas=( \
				"--tab-with-profile=projects:cli --title=/cli --working-directory=/projects/cli" \
				"--tab-with-profile=projects:cli --title=console.pallet --working-directory=/projects/cli/console.pallet" \
				"--tab-with-profile=projects:cli --title=alacast-cli --working-directory=/projects/cli/alacast" \
				"--tab-with-profile=projects:art --title=/art --working-directory=/projects/art" \
				"--tab-with-profile=projects:www --title=/www --working-directory=/projects/www" \
				"--tab-with-profile=projects:www --title=a.o.php --working-directory=/projects/www/uberChicGeekChick.Com" \
				"--tab-with-profile=projects:gtk --title=/gtk --working-directory=/projects/gtk" \
				"--tab-with-profile=projects:gtk --title=connectED --working-directory=/projects/gtk/connectED" \
				"--tab-with-profile=projects:gtk --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
				"--tab-with-profile=projects:gtk --title=alacast-gtk --working-directory=/projects/gtk/alacast" \
				"--tab-with-profile=projects:games --title=/games --working-directory=/projects/games" \
				"--tab-with-profile=projects:games --title=many-worlds --working-directory=/projects/games/my-games/many-worlds" \
			);
			breaksw;
		
		case "Artistic":
		default:
			set my_canvas=( \
				"--tab-with-profile=projects:cli --title=console.pallet> --working-directory=/projects/cli/console.pallet" \
				"--tab-with-profile=projects:www --title=a.o.php --working-directory=/projects/www/uberChicGeekChick.Com" \
				"--tab-with-profile=projects:media --title=media --working-directory=/media" \
				#"--tab-with-profile=projects:gtk --title=connectED --working-directory=/projects/gtk/connectED" \
				"--tab-with-profile=projects:gtk --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
				"--tab-with-profile=projects:gtk --title=alacast.v2 --working-directory=/projects/gtk/alacast" \
				"--tab-with-profile=projects:games --title=many-worlds --working-directory=/projects/games/my-games/many-worlds" \
			);
			breaksw;
		endsw
goto next_canvas


build_canvas:
	set with_screen;
	switch( "${canvas}" )
	case  "Mozilla":
		set my_canvas=( \
			"--tab-with-profile=uberChick --title=mozilla-src --working-directory=/programs/mozilla/src" \
			"--tab-with-profile=uberChick --title=xulrunner-src --working-directory=/programs/mozilla/src/xulrunner-srcdir" \
			"--tab-with-profile=uberChick --title=firefox-src --working-directory=/programs/mozilla/src/firefox-srcdir" \
			"--tab-with-profile=uberChick --title=thunderbird-src --working-directory=/programs/mozilla/src/thunderbird-srcdir" \
		);
		breaksw;
	
	case  "XULRunner":
		set my_canvas=( \
			"--tab-with-profile=uberChick --title=xulrunner-src --working-directory=/programs/mozilla/src/xulrunner-srcdir" \
		);
		breaksw;

	case  "Canvas":
	default:
		set my_canvas=( \
			"--tab-with-profile=uberChick --title=/projects --working-directory=/projects" \
			"--tab-with-profile=uberChick --title=mozilla/src --working-directory=/programs/mozilla/src" \
			"--tab-with-profile=uberChick --title=build:canvas --working-directory=/programs/src" \
		);
		breaksw;
	
	endsw
goto next_canvas



media_canvas:
	switch ( "${canvas}" )
	case  "Alacast":
		set my_canvas=( \
			"--tab-with-profile=alacast:php --title=alacast:php --working-directory=/projects/cli/alacast --command=/projects/cli/alacast/bin/alacast.php --logging --titles-append-pubdate --player--strip-characters='!#' --update=detailed --interactive" \
		);
		breaksw;
	case  "Online":
		set with_screen;
		set with_ssh_our_eee;
		set with_ssh_dreams;
		if( -e "${HOME}/.rtorrent.rc" ) then
			set rtorrent_session_dir = `/bin/grep 'session' "${HOME}/.rtorrent.rc" | /bin/sed 's/^[^=]\+=\ \(.*\)$/\1/g'`;
			if( "${rtorrent_session_dir}" != "" && -d "${rtorrent_session_dir}" ) then
				rm -f "${rtorrent_session_dir}/rtorrent.lock";
				rm -f "${rtorrent_session_dir}/rtorrent.dht_cache";
			endif
		endif
		
		set my_canvas=( \
			"--tab-with-profile=rTorrent --title=rtorrent --working-directory=/media/torrents --command=rtorrent" \
			"--tab-with-profile=uberChick --title=/projects/media --working-directory=/projects/media" \
			"--tab-with-profile=uberChick --title=/media --working-directory=/media" \
			"--tab-with-profile=uberChick --title=podcasts --working-directory=/media/podcasts" \
			"--tab-with-profile=project --title=alacast --working-directory=/projects/cli/alacast" \
			"--tab-with-profile=alacast:php --title=alacast:php --working-directory=/projects/cli/alacast --command=/projects/cli/alacast/bin/alacast.php --logging --titles-append-pubdate --strip-characters='#;!' --update=detailed --interactive" \
		);
		breaksw;
	endsw
goto next_canvas


editor_canvas:
	switch ( "${canvas}" )
	case  "Template":
		set mycanvas = ( \
			"--tab --title=~ --working-directory='${HOME}'" \
		);
		breaksw;
	
	case  "VIM":
		set my_canvas = ( \
			"--tab-with-profile=uberChick --title=vim --working-directory=/projects --command='vim-enhanced -p ${argv}'" \
		);
		unset argv;
		breaksw;
		
	case  "Default":
	default:
		set my_canvas = ( \
			"--tab-with-profile=uberChick --title=${EDITOR} --working-directory=/projects --command='${EDITOR} -p ${argv}'" \
		);
		unset argv;
		breaksw;
	endsw
goto next_canvas


default_canvas:
	switch ( "${canvas}" )
	case  "Screen":
		set with_screen;
		set with_ssh_our_eee;
		set with_ssh_dreams;
		set my_canvas="";
		breaksw;
	default:
		#set with_screen;
		#set with_ssh_our_eee;
		#set with_ssh_dreams;
		set with_home;
		set my_canvas="";
		breaksw;
	endsw
goto next_canvas

next_canvas:
	if( ${?my_canvas} ) then
		if(! ${?with_screen} ) then
			set with_screen="";
		else
			set with_screen="--tab-with-profile=screen";
			if( -e "${HOME}/.rtorrent.rc" ) then
				set rtorrent_session_dir = `/bin/grep 'session' "${HOME}/.rtorrent.rc" | /bin/sed 's/^[^=]\+=\ \(.*\)$/\1/g'`;
				if( "${rtorrent_session_dir}" != "" && -d "${rtorrent_session_dir}" ) then
					rm -f "${rtorrent_session_dir}/rtorrent.lock";
					rm -f "${rtorrent_session_dir}/rtorrent.dht_cache";
				endif
			endif
		endif
		
		if(! ${?with_ssh_dreams} ) then
			set with_ssh_dreams="";
		else
			set with_ssh_dreams="--tab-with-profile=ssh:dreams";
		endif
		
		if(! ${?with_ssh_our_eee} ) then
			set with_ssh_our_eee="";
		else
			set with_ssh_our_eee="--tab-with-profile=ssh:our-eee";
		endif
		
		if(! ${?with_home} ) then
			set with_home="";
		else
			set with_home="--tab-with-profile=${USER} --title=~ --working-directory=${HOME}";
		endif
		
		foreach working_directory("`echo '${my_canvas}'`")
			set canvas_directory="`printf '%s' '${working_directory}' | sed -r 's/.*\-\-working\-directory\=["\""'\'']?([^\ ]*)["\""'\'']?.*${eol}/\1/'`";
			if( "${canvas_directory}" == "${working_directory}" ) continue;
			echo "${canvas_directory}";
			if( -d "${canvas_directory}" ) continue;
			echo "${canvas_directory}";
			mkdir -p "${canvas_directory}";
		end
		unset canvas_directory working_directory;
		
		/usr/bin/gnome-terminal --hide-menubar --geometry=${geometry} --role=${canvas_role}	\
			${with_screen}									\
			${with_ssh_dreams}								\
			${with_ssh_our_eee}								\
			${with_home}									\
			${my_canvas}									\
		${argv} &;
		unset my_canvas with_screen with_ssh_dreams with_ssh_our_eee with_home;
	endif
end

