#!/bin/tcsh -f
set resolutions_path="`dirname '${0}'`/../resolutions/gnome-terminal";

set default_geometry=`cat "${resolutions_path}/default.rc"`;
set build_geometry=`cat "${resolutions_path}/build.rc"`;
set programming_geometry=`cat "${resolutions_path}/programming.rc"`;
set media_geometry=`cat "${resolutions_path}/media.rc"`;
set canvas_geometry=`cat "${resolutions_path}/canvas.rc"`;
set editor_geometry = `cat "${resolutions_path}/editor.rc"`;

set screens_command="/projects/cli/helpers/screen:attach";

foreach canvas_info ( "${argv}" )
	
	if(! ${?my_default_tabs} ) \
		set my_default_tabs = ( \
			"--tab-with-profile=screen --title=:screen: --working-directory=~/ --command=${screens_command}" \
			"--tab-with-profile=uberChick --title=/ssh --working-directory=/projects/ssh" \
			"--tab-with-profile=uberChick --title=~/ --working-directory=${HOME}" \
		);
	
	set canvas_type="`printf '${canvas_info}' | sed 's/^\([^:]\+\):\(.*\)/\1/g'`";
	set canvas="`printf '${canvas_info}' | sed 's/^\([^:]\+\):\(.*\)/\2/g'`";
	switch( "${canvas_type}" )
	case "Editor":
		shift;
		set geometry="${editor_geometry}";
		goto  editor_canvas
		breaksw
	case "Canvas":
		shift;
		set geometry="${canvas_geometry}";
		goto  canvas_canvas
		breaksw
	case "Programming":
		shift;
		set geometry="${programming_geometry}"
		goto  programming_canvas
		breaksw
	case "Media":
		shift;
		set geometry="${media_geometry}"
		goto media_canvas
		breaksw
	case "Build":
		shift;
		set geometry="${build_geometry}"
		goto build_canvas
		breaksw
	default:
		set geometry="${default_geometry}"
		goto  default_canvas
		breaksw
	endsw


	
	
editor_canvas:
	switch ( "${canvas}" )
	case 'Template':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			${my_projects} \
		${argv} &;
		breaksw
	
	case 'VIM':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="vim-enhanced" --working-directory="/projects" --command="/usr/bin/vim-enhanced -p ${argv}" \
		&;
		breaksw
		
	case 'Default':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="${EDITOR}" --working-directory="/projects" --command="${EDITOR} -p ${argv}" \
		&;
		breaksw
	endsw
goto next_canvas

	
	
programming_canvas:
	if(! ${?my_projects} ) \
		set my_projects = ( \
					"--tab-with-profile=uberChick --title=/cli --working-directory=/projects/cli" \
					"--tab-with-profile=uberChick --title=/reference --working-directory=/projects/reference" \
					"--tab-with-profile=uberChick --title=/www --working-directory=/projects/www" \
					"--tab-with-profile=uberChick --title=/games --working-directory=/projects/games" \
					"--tab-with-profile=uberChick --title=/gtk --working-directory=/projects/gtk" \
		);

	if(! ${?my_active_projects} ) \
		set my_active_projects=( \
					"--tab-with-profile=uberChick --title=AOPHP --working-directory=/projects/www/uberChicGeekChick.Com" \
					"--tab-with-profile=uberChick --title=hackGirls --working-directory=/projects/games/hackGirls" \
					"--tab-with-profile=uberChick --title=connectED --working-directory=/projects/gtk/connectED" \
					"--tab-with-profile=uberChick --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
					"--tab-with-profile=uberChick --title=alacast --working-directory=/projects/gtk/alacast" \
		);

	if(! ${?my_games} ) \
		set my_games=( \
					"--tab-with-profile=uberChick --title=/games --working-directory=/projects/games" \
					"--tab-with-profile=uberChick --title=game-dev:engines --working-directory=/projects/games/engines" \
					"--tab-with-profile=uberChick --title=game-dev:libraries --working-directory=/projects/games/libraries" \
					"--tab-with-profile=uberChick --title=game-dev:tools --working-directory=/projects/games/tools" \
					"--tab-with-profile=uberChick --title=many-worlds --working-directory=/projects/games/many-worlds" \
					"--tab-with-profile=uberChick --title=puzzling-galaxsee --working-directory=/projects/games/puzzling-galaxsee" \
					"--tab-with-profile=uberChick --title=hackGirls --working-directory=/projects/games/hackGirls" \
		);

	if(! ${?my_gtk_projects} ) \
		set my_gtk_projects=( \
					"--tab-with-profile=uberChick --title=/gtk --working-directory=/projects/gtk" \
					"--tab-with-profile=uberChick --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
					"--tab-with-profile=uberChick --title=connectED --working-directory=/projects/gtk/connectED" \
					"--tab-with-profile=uberChick --title=Alacast --working-directory=/projects/gtk/alacast" \
		);

	if(! ${?my_www_projects} ) \
		set my_www_projects = ( \
					"--tab-with-profile=uberChick --title=/srv --working-directory=/srv" \
					"--tab-with-profile=uberChick --title=/www --working-directory=/projects/www" \
					"--tab-with-profile=uberChick --title=TweetMyBlog --working-directory=/projects/www/TweetMyBlog" \
					"--tab-with-profile=uberChick --title=realFriends --working-directory=/projects/www/realFriends" \
					"--tab-with-profile=uberChick --title=Dystonia-DREAMS.org --working-directory=/projects/www/Dystonia-DREAMS.Org" \
					"--tab-with-profile=uberChick --title=uberChicks.net --working-directory=/projects/www/uberChicks.Net" \
					"--tab-with-profile=uberChick --title=AOPHP --working-directory=/projects/www/uberChicGeekChick.Com" \
		);

	if(! ${?my_cli_projects} ) \
		set my_cli_projects=( \
					"--tab-with-profile=uberChick --title=/cli --working-directory=/projects/cli" \
					"--tab-with-profile=uberChick --title=/profile.d --working-directory=/profile.d" \
					"--tab-with-profile=uberChick --title=tcshrc-dev --working-directory=/projects/cli/tcsh-dev/tcshrc-dev" \
		);

	switch( "${canvas}" )
	case 'All':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			${my_projects} \
			${my_cli_projects} \
			${my_gtk_projects} \
			${my_games} \
		${argv} &;
		breaksw
	
	case 'GTK':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			${my_gtk_projects} \
		${argv} &;
		breaksw;

	case 'CLI':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			${my_cli_projects} \
		${argv} &;
		breaksw;
	
	case 'Games':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			--tab-with-profile="OpenSim" --title="OpenSim" --working-directory="/projects/games/tools/OpenSim/bin" --command="/projects/games/bin/OpenSim.tcsh" \
			${my_games} \
		${argv} &;
		breaksw
	
	case 'WWW':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			${my_www_projects} \
		${argv} &;
		breaksw
	
	case 'Projects':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			${my_projects} \
			${my_active_projects} \
		${argv} &;
		breaksw
	endsw
goto next_canvas



build_canvas:
	switch( "${canvas}" )
	case 'Programs':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="/programs/src" --working-directory="/programs/src" \
		${argv} &;
		breaksw
	
	case 'Projects':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="/projects" --working-directory="/projects" \
		${argv} &;
		breaksw
	
	case 'Mozilla':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="mozilla-src" --working-directory="/programs/src/mozilla" \
		${argv} &;
		breaksw
	
	case 'Firefox':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="firefox-src" --working-directory="/programs/src/mozilla/firefox-src" \
		${argv} &;
		breaksw
	
	case 'Thunderbird':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="thunderbird-src" --working-directory="/programs/src/mozilla/thunderbird-src" \
		${argv} &;
		breaksw
	
	case 'Canvas':
	default:
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="uberChick" --title="/profile.d" --working-directory="/profile.d" \
			--tab-with-profile="uberChick" --title="tcsh-dev" --working-directory="/projects/cli/tcsh-dev/tcsh-dev" \
			--tab-with-profile="uberChick" --title="/projects" --working-directory="/projects" \
			--tab-with-profile="uberChick" --title="/programs/src" --working-directory="/programs/src" \
		${argv} &;
		breaksw
	
	endsw
goto next_canvas

	
	
media_canvas:
	switch ( "${canvas}" )
	case 'Production':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
			--tab-with-profile="uberChick" --title="art" --working-directory="/projects/art" \
			--tab-with-profile="uberChick" --title="Alacast" --working-directory="/projects/gtk/alacast" \
			--tab-with-profile="uberChick" --title="/media-library" --working-directory="/media/media-library" \
			--tab-with-profile="uberChick" --title="my podcasts" --working-directory="/projects/media/podcasts" \
		${argv} &;
		breaksw

	case 'Social':
		if ( -e "${HOME}/.rtorrent.rc" ) then
			set rtorrent_session_dir = `/usr/bin/grep 'session' "${HOME}/.rtorrent.rc" | /usr/bin/sed 's/^[^=]\+=\ \(.*\)$/\1/g'`;
			if ( "${rtorrent_session_dir}" != "" && -d "${rtorrent_session_dir}" ) then
				rm -f "${rtorrent_session_dir}/rtorrent.lock";
				rm -f "${rtorrent_session_dir}/rtorrent.dht_cache";
			endif
		endif
		
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="rTorrent" --title="rTorrent" --working-directory="/media/torrents" --command="rtorrent"  \
			--tab-with-profile="screen" \
			--tab-with-profile="uberChick" --title="/projects/media" --working-directory="/projects/media" \
			--tab-with-profile="uberChick" --title="/media" --working-directory="/media" \
			--tab-with-profile="uberChick" --title="podiobooks" --working-directory="/media/podiobooks" \
			--tab-with-profile="uberChick" --title="podcasts" --working-directory="/media/podcasts" \
			--tab-with-profile="uberChick" --title="alacast:php" --working-directory="/projects/cli/alacast" --command="/projects/cli/alacast/bin/alacast.php --update=detailed --logging --player=xine --interactive" \
		${argv} &;
		breaksw
	endsw
goto next_canvas
	
	
	
default_canvas:
	switch ( "${canvas}" )
	case 'Screen':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="screen"  \
		${argv} &;
		breaksw
	default:
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_default_tabs} \
		${argv} &;
		breaksw
	endsw
goto next_canvas

	
	
next_canvas:
end

