#!/bin/tcsh -f
set resolutions_path="`dirname '${0}'`/../resolutions/gnome-terminal";

set default_geometry=`cat "${resolutions_path}/default.rc"`;
set build_geometry=`cat "${resolutions_path}/build.rc"`;
set artistic_geometry=`cat "${resolutions_path}/artistic.rc"`;
set media_geometry=`cat "${resolutions_path}/media.rc"`;
set canvas_geometry=`cat "${resolutions_path}/canvas.rc"`;
set editor_geometry = `cat "${resolutions_path}/editor.rc"`;

set screens_command="/projects/cli/helpers/screen:attach";

foreach canvas ( "${argv}" )
	
	set my_gnome_terminal="/usr/bin/gnome-terminal --hide-menubar --role='${canvas}'";
	set canvas_type="`printf '${canvas}' | sed 's/^\([^:]\+\):\(.*\)/\1/g'`";
	set canvas="`printf '${canvas}' | sed 's/^\([^:]\+\):\(.*\)/\2/g'`";
	
	switch( "${canvas_type}" )
	case "Editor":
		shift;
		set geometry="${editor_geometry}";
		goto  editor_canvas
		breaksw;
	
	case "Canvas":
		shift;
		set geometry="${canvas_geometry}";
		goto  canvas_canvas
		breaksw;
	
	case "Artistic":
		shift;
		set geometry="${artistic_geometry}"
		goto  artistic_canvas
		breaksw;
	
	case "Media":
		shift;
		set geometry="${media_geometry}"
		goto media_canvas
		breaksw;
	
	case "Build":
		shift;
		set geometry="${build_geometry}"
		goto build_canvas
		breaksw;
	
	case "Default":
	default:
		set geometry="${default_geometry}"
		goto  default_canvas
		breaksw;
	endsw

goto next_canvas
	
	
editor_canvas:
	switch ( "${canvas}" )
	case 'Template':
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
		${argv} &;
		breaksw;
	
	case 'VIM':
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile="uberChick" --title="vim-enhanced" --working-directory="/projects" --command="/usr/bin/vim-enhanced -p ${argv}" \
		&;
		breaksw;
		
	case 'Default':
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile="uberChick" --title="${EDITOR}" --working-directory="/projects" --command="${EDITOR} -p ${argv}" \
		&;
		breaksw;
	endsw
goto next_canvas


artistic_canvas:
	if(! ${?my_projects} ) \
		set my_projects=( \
					"--tab-with-profile=uberChick --title=/cli --working-directory=/projects/cli" \
					"--tab-with-profile=uberChick --title=/www --working-directory=/projects/www" \
					"--tab-with-profile=uberChick --title=/gtk --working-directory=/projects/gtk" \
					"--tab-with-profile=uberChick --title=/art --working-directory=/projects/art" \
					"--tab-with-profile=uberChick --title=/games --working-directory=/projects/games" \
		);

	if(! ${?my_active_projects} ) \
		set my_active_projects=( \
					"--tab-with-profile=uberChick --title=AOPHP --working-directory=/projects/www/uberChicGeekChick.Com" \
					"--tab-with-profile=uberChick --title=connectED --working-directory=/projects/gtk/connectED" \
					"--tab-with-profile=uberChick --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
					"--tab-with-profile=uberChick --title=alacast --working-directory=/projects/gtk/alacast" \
					"--tab-with-profile=uberChick --title=many-worlds --working-directory=/projects/games/many-worlds" \
		);
	
	switch( "${canvas}" )
		case 'Projects':
			${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
				${my_projects} \
		${argv} &;
		breaksw;																		
	case 'Games':
		if(! ${?my_games} ) \
			set my_games=( \
					"--tab-with-profile=uberChick --title=/art --working-directory=/projects/art" \
					"--tab-with-profile=uberChick --title=/games --working-directory=/projects/games" \
					"--tab-with-profile=uberChick --title=game-dev:engines --working-directory=/projects/games/engines" \
					"--tab-with-profile=uberChick --title=game-dev:libraries --working-directory=/projects/games/libraries" \
					"--tab-with-profile=uberChick --title=game-dev:tools --working-directory=/projects/games/tools" \
					"--tab-with-profile=uberChick --title=hackGirls --working-directory=/projects/games/hackGirls" \
					"--tab-with-profile=uberChick --title=many-worlds --working-directory=/projects/games/many-worlds" \
			);
		
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
			#--tab-with-profile="OpenSim" --title="OpenSim" --working-directory="/projects/games/tools/OpenSim/bin" --command="/projects/games/bin/OpenSim.tcsh" \
			${my_games} \
		${argv} &;
		breaksw;
	
	case 'GTK':
	if(! ${?my_gtk_projects} ) \
		set my_gtk_projects=( \
					"--tab-with-profile=uberChick --title=/gtk --working-directory=/projects/gtk" \
					"--tab-with-profile=uberChick --title=connectED --working-directory=/projects/gtk/connectED" \
					"--tab-with-profile=uberChick --title=get2gnow --working-directory=/projects/gtk/get2gnow" \
					"--tab-with-profile=uberChick --title=alacast --working-directory=/projects/gtk/alacast" \
		);
		
		printf "-->%s\n" $canvas;
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
			${my_gtk_projects} \
		${argv} &;
		breaksw;

	case 'CLI':
		if(! ${?my_cli_projects} ) \
			set my_cli_projects=( \
						"--tab-with-profile=uberChick --title=/cli --working-directory=/projects/cli" \
						"--tab-with-profile=uberChick --title=/profile.d --working-directory=/profile.d" \
						"--tab-with-profile=uberChick --title=tcshrc-dev --working-directory=/projects/cli/tcsh-dev/tcshrc-dev" \
			);
		
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
			${my_cli_projects} \
		${argv} &;
		breaksw;
	
	case 'WWW':
		if(! ${?my_www_projects} ) \
			set my_www_projects=( \
						"--tab-with-profile=uberChick --title=/www --working-directory=/projects/www" \
						"--tab-with-profile=uberChick --title=online-oss --working-directory=/projects/www/online-oss" \
						"--tab-with-profile=uberChick --title=TweetMyBlog --working-directory=/projects/www/TweetMyBlog" \
						"--tab-with-profile=uberChick --title=realFriends --working-directory=/projects/www/realFriends" \
						"--tab-with-profile=uberChick --title=Creative::Code::Canvas --working-directory=/projects/www/Creative::Code::Canvas" \
						"--tab-with-profile=uberChick --title=AOPHP --working-directory=/projects/www/uberChicGeekChick.Com" \
					);
		
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
			${my_www_projects} \
		${argv} &;
		breaksw;
	
	case 'MyWebSites':
		if(! ${?my_websites} ) \
			set my_websites=( \
				"--tab-with-profile=uberChick --title=uberChicks.Net --working-directory=/projects/www/uberChicks.Net" \
				"--tab-with-profile=uberChick --title=Dystonia-DREAMS.Org --working-directory=/projects/www/Dystonia-DREAMS.Org" \
				"--tab-with-profile=uberChick --title=uberChicGeekChick.Com --working-directory=/projects/www/uberChicGeekChick.Com" \
			);
		
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
			${my_websites} \
		${argv} &;
		breaksw;
	case 'GraphicArt':
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
			--tab-with-profile="uberChick" --title="/media-library" --working-directory="/media/library" \
			--tab-with-profile="uberChick" --title="/projects/media" --working-directory="/projects/media" \
			--tab-with-profile="uberChick" --title="/art" --working-directory="/projects/art" \
		${argv} &;
		breaksw;
	
	case 'All':
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
			${my_projects} \
			${my_active_projects} \
		${argv} &;
		breaksw;
	endsw
goto next_canvas


build_canvas:
	switch( "${canvas}" )
	case 'Mozilla':
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile="build:canvas" --title="mozilla-src" --working-directory="/programs/Mozilla/src" \
			--tab-with-profile="build:canvas" --title="thunderbird-src" --working-directory="/programs/Mozilla/thunderbird-src" \
			--tab-with-profile="build:canvas" --title="firefox-src" --working-directory="/programs/Mozilla/fsrc/irefox-src" \
			--tab-with-profile="build:canvas" --title="xulrunner-src" --working-directory="/programs/Mozilla/fsrc/xulrunner-src" \
		${argv} &;
		breaksw;
	
	case 'XUL-Runner':
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile="build:canvas" --title="xulrunner-src" --working-directory="/programs/Mozilla/fsrc/xulrunner-src" \
		${argv} &;
		breaksw;

												case 'Firefox':
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile="build:canvas" --title="firefox-src" --working-directory="/programs/Mozilla/src/firefox-src" \
		${argv} &;
		breaksw;
	
	case 'Thunderbird':
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile="build:canvas" --title="thunderbird-src" --working-directory="/programs/Mozilla/src/thunderbird-src" \
		${argv} &;
		breaksw;
	
	case 'Canvas':
	default:
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile="build:canvas" --title="/programs/src" --working-directory="/programs/src" \
			--tab-with-profile="build:canvas" --title="xulrunner-src" --working-directory="/programs/Mozilla/fsrc/xulrunner-src" \
			--tab-with-profile="build:canvas" --title="firefox-src" --working-directory="/programs/Mozilla/src/firefox-src" \
			--tab-with-profile="build:canvas" --title="thunderbird-src" --working-directory="/programs/Mozilla/src/thunderbird-src" \
			--tab-with-profile="build:canvas" --title="/projects" --working-directory="/projects" \
			--tab-with-profile="build:canvas" --title="/programs/src" --working-directory="/programs/src" \
		${argv} &;
		breaksw;
	
	endsw
goto next_canvas

	
	
media_canvas:
	switch ( "${canvas}" )
	case 'Online':
		if ( -e "${HOME}/.rtorrent.rc" ) then
			set rtorrent_session_dir = `/usr/bin/grep 'session' "${HOME}/.rtorrent.rc" | /usr/bin/sed 's/^[^=]\+=\ \(.*\)$/\1/g'`;
			if ( "${rtorrent_session_dir}" != "" && -d "${rtorrent_session_dir}" ) then
				rm -f "${rtorrent_session_dir}/rtorrent.lock";
				rm -f "${rtorrent_session_dir}/rtorrent.dht_cache";
			endif
		endif
		
		${my_gnome_terminal} --geometry=${geometry} \
			--tab-with-profile='[screen]$>' \
			--tab-with-profile="rTorrent" --title="rTorrent" --working-directory="/media/torrents" --command="rtorrent"  \
			--tab-with-profile="uberChick" --title="xhtml-profiles" --working-directory="/projects/www/online-profiles" \
			--tab-with-profile="uberChick" --title="/projects/media" --working-directory="/projects/media" \
			--tab-with-profile="uberChick" --title="/media" --working-directory="/media" \
			--tab-with-profile="uberChick" --title="podiobooks" --working-directory="/media/podiobooks" \
			--tab-with-profile="uberChick" --title="podcasts" --working-directory="/media/podcasts" \
			--tab-with-profile="alacast:php" --title="alacast:php" --working-directory="/projects/cli/alacast" --command="/projects/cli/alacast/bin/alacast.php --update=detailed --logging --player=xine --interactive --titles-append-pubdate" \
		${argv} &;
		breaksw;
	endsw
goto next_canvas
	
	
	
default_canvas:
	switch ( "${canvas}" )
	case 'Screen':
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>'  \
		${argv} &;
		breaksw;
	default:
		${my_gnome_terminal} --geometry=${geometry} --tab-with-profile='[screen]$>' \
		${argv} &;
		breaksw;
	endsw
goto next_canvas

next_canvas:
	if( ${?my_canvas} ) then
		${my_gnome_terminal} --geometry=${geometry} ${my_canvas} ${argv} &;
		unset my_canvas;
	endif
end

