#!/bin/tcsh -f
set resolutions_path="/profile.d/resolutions/gnome-terminal";

set default_geometry=`cat "${resolutions_path}/default.rc"`;
set tiny_geometry=`cat "${resolutions_path}/tiny.rc"`;
set programming_geometry=`cat "${resolutions_path}/programming.rc"`;
set media_geometry=`cat "${resolutions_path}/media.rc"`;
set canvas_geometry=`cat "${resolutions_path}/canvas.rc"`;
set editor_geometry = `cat "${resolutions_path}/editor.rc"`;

set screen_command="/usr/bin/screen -aAUR";
set screens_options="aAUR";
set screens_sessions=`/usr/bin/screen -list`;
if ( "$screens_sessions[1]" != "No" ) then
	set screen_command="${screen_command}x";
	set screens_options="${screens_options}x";
endif
alias screen "${screen_command}";
unset sceen_command;
unset screens_sessions;

set default_tabs = ( "--tab-with-profile=screen --title=:screen: --command=screen" \
	"--tab-with-profile=projects --title=/profile.d --working-directory=/profile.d" \
	"--tab-with-profile=projects --title=/media --working-directory=/media" \
	"--tab-with-profile=projects --title=~/ --working-directory=${HOME}" \
	"--tab-with-profile=projects --title=/ssh --working-directory=/projects/ssh" \
	"--tab-with-profile=projects --title=/srv --working-directory=/srv" \
	"--tab-with-profile=projects --title=/programs --working-directory=/programs" \
	"--tab-with-profile=projects --title=/projects --working-directory=/projects" \
);

set my_projects = ( "--tab-with-profile=screen --title=:screen: --command=screen" \
	"--tab-with-profile=projects --title=projects --working-directory=/projects" \
       	"--tab-with-profile=projects --title=/ssh --working-directory=/projects/ssh" \
	"--tab-with-profile=projects --title=tcshrc-dev --working-directory=/projects/console/tcshrc-dev" \
	"--tab-with-profile=projects --title=alacast:cli --working-directory=/projects/gtk/alacast" \
	"--tab-with-profile=projects --title=AOPHP --working-directory=/projects/www/MyWebDesigns/uberChicGeekChick.Com" \
	"--tab-with-profile=projects --title=ManyWorlds --working-directory=/projects/games/ManyWorlds" \
	"--tab-with-profile=projects --title=twitux --working-directory=/projects/gtk/twitux" \
	"--tab-with-profile=projects --title=alacast:gtk --working-directory=/projects/gtk/alacast" \
	"--tab-with-profile=projects --title=connectED --working-directory=/projects/gtk/connectED" \
);


foreach canvas_info ( "${argv}" )
	set geometry="${default_geometry}"
	set canvas_type="`printf '${canvas_info}' | sed 's/^\([^:]\+\):\(.*\)/\1/g'`";
	set canvas="`printf '${canvas_info}' | sed 's/^\([^:]\+\):\(.*\)/\2/g'`";
	switch( "${canvas_type}" )
	case "Editor":
		shift;
		set geometry="${editor_geometry}";
		goto  editor_canvas
		breaksw
	case "Canvas":
		shift;
		set geometry="${canvas_geometry}";
		goto  canvas_canvas
		breaksw
	case "Programming":
		shift;
		set geometry="${programming_geometry}"
		goto  programming_canvas
		breaksw
	case "Media":
		shift;
		set geometry="${media_geometry}"
		goto media_canvas
		breaksw
	default:
		set geometry="${default_geometry}"
		goto  default_canvas
		breaksw
	endsw


	
	
editor_canvas:
	switch ( "${canvas}" )
	case 'Template':
		if ( "${?screens_started}" == "0" ) set screens_started;
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${default_tabs} \
			${my_projects} \
		${argv} &;
		breaksw
	
	case 'VIM':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="projects" --title="vim-enhanced" --working-directory="/projects" --command="/usr/bin/vim-enhanced -p ${argv}" \
		&;
		breaksw
		
	case 'Default':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="projects" --title="${EDITOR}" --working-directory="/projects" --command="${EDITOR} -p ${argv}" \
		&;
		breaksw
	endsw
goto next_canvas

	
	
programming_canvas:
	if ( "${?screens_started}" == "0" ) set screens_started;
	switch( "${canvas}" )
	case 'All':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_projects} \
			--tab-with-profile="projects" --title="cli" --working-directory="/projects/console" \
			--tab-with-profile="projects" --title="gtk" --working-directory="/projects/gtk" \
			--tab-with-profile="projects" --title="art" --working-directory="/projects/art" \
			--tab-with-profile="projects" --title="www" --working-directory="/projects/www" \
			--tab-with-profile="projects" --title="media" --working-directory="/projects/media" \
			--tab-with-profile="projects" --title="games" --working-directory="/projects/games" \
			--tab-with-profile="projects" --title="/profile.d" --working-directory="/profile.d" \
		${argv} &;
		breaksw
	
	case 'Apps':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_projects} \
			--tab-with-profile="projects" --title="art" --working-directory="/projects/art" \
			--tab-with-profile="projects" --title="cli" --working-directory="/projects/console" \
			--tab-with-profile="projects" --title="gtk" --working-directory="/projects/gtk" \
		${argv} &;
		breaksw
	
	case 'Games':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_projects} \
			--tab-with-profile="projects" --title="media-library" --working-directory="/media/media-library" \
			--tab-with-profile="projects" --title="tools" --working-directory="/projects/games/tools" \
			--tab-with-profile="projects" --title="engines" --working-directory="/projects/games/engines" \
			--tab-with-profile="projects" --title="libraries" --working-directory="/projects/games/libraries" \
			--tab-with-profile="projects" --title="Raydium" --working-directory="/projects/games/engines/Raydium" \
			--tab-with-profile="projects" --title="art" --working-directory="/projects/art" \
			--tab-with-profile="projects" --title="game-design" --working-directory="/projects/games" \
		${argv} &;
		breaksw
	
	case 'Internet':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_projects} \
			--tab-with-profile="projects" --title="reference" --working-directory="/projects/reference" \
			--tab-with-profile="projects" --title="art" --working-directory="/projects/art" \
			--tab-with-profile="projects" --title="AOPHP" --working-directory="/projects/www/uberChicGeekChick.Com" \
		${argv} &;
		breaksw
	
	case 'Build':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${tiny_geometry} \
			--tab-with-profile="screen" --title=":screen:" --command="/usr/bin/screen -${screens_options}"  \
			--tab-with-profile="projects" --title="/programs/src" --working-directory="/programs/src" \
			--tab-with-profile="projects" --title="firefox-src" --working-directory="/programs/Mozilla/src/firefox-src" \
			--tab-with-profile="projects" --title="thunderbird-src" --working-directory="/programs/Mozilla/src/thunderbird-src" \
		${argv} &;
		breaksw
	
	case 'Projects':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${my_projects} \
		${argv} &;
		breaksw
	endsw
goto next_canvas

	
	
media_canvas:
	if ( "${?screens_started}" == "0" ) set screens_started;
	switch ( "${canvas}" )
	case 'Production':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${tiny_geometry} \
			${default_tabs} \
			--tab-with-profile="projects" --title="art" --working-directory="/projects/art" \
			--tab-with-profile="projects" --title="alacast:gtk" --working-directory="/projects/gtk/alacast" \
			--tab-with-profile="projects" --title="/media-library" --working-directory="/media/media-library" \
			--tab-with-profile="projects" --title="my podcasts" --working-directory="/projects/media/podcasts" \
		${argv} &;
		breaksw

	case 'Social':
		if ( -e "${HOME}/.rtorrent.rc" ) then
			set rtorrent_session_dir = `/usr/bin/grep 'session' "${HOME}/.rtorrent.rc" | /usr/bin/sed 's/^[^=]\+=\ \(.*\)$/\1/g'`;
			if ( "${rtorrent_session_dir}" != "" && -d "${rtorrent_session_dir}" ) then
				rm -f "${rtorrent_session_dir}/rtorrent.lock";
				rm -f "${rtorrent_session_dir}/rtorrent.dht_cache";
			endif
		endif
		
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			--tab-with-profile="rTorrent" --title="rTorrent" --working-directory="/media/torrents" --command="rtorrent"  \
			--tab-with-profile="screen" --title=":screen:" --command="/usr/bin/screen -${screens_options}"  \
			--tab-with-profile="projects" --title="/projects" --working-directory="/projects" \
			--tab-with-profile="projects" --title="alacast:cli" --working-directory="/projects/console/alacast" \
			--tab-with-profile="projects" --title="alacast:gtk" --working-directory="/projects/gtk/alacast" \
			--tab-with-profile="projects" --title="/media" --working-directory="/media" \
			--tab-with-profile="projects" --title="podiobooks" --working-directory="/media/podiobooks" \
			--tab-with-profile="projects" --title="podcasts" --working-directory="/media/podcasts" \
			--tab-with-profile="projects" --title="alacast:php" --working-directory="/projects/console/alacast" --command="/projects/console/alacast/bin/alacast.php --update=detailed --logging --player=xine --interactive" \
		${argv} &;
		breaksw
	endsw
goto next_canvas
	
	
	
default_canvas:
	if ( "${?screens_started}" == "0" ) set screens_started;
	switch ( "${canvas}" )
	case 'Screen':
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${tiny_geometry} \
			--tab-with-profile="screen" --title="[screen]" --command="/usr/bin/screen -${screens_options}"  \
		${argv} &;
		breaksw
	default:
		/usr/bin/gnome-terminal \
			--hide-menubar \
			--geometry=${geometry} \
			${default_tabs} \
		${argv} &;
		breaksw
	endsw
goto next_canvas

	
	
next_canvas:
	if ( "${?screens_started}" == "1" ) then
		set screen_command="/usr/bin/screen -aAURx";
		set screens_options="aAURx";
	endif
end
