#!/bin/tcsh -f
gnome-terminal --geometry=80x20 \
	--tab-with-profile='uberChick#>' --hide-menubar --title='~' --working-directory='~' \
	--tab-with-profile='screen#>' --hide-menubar --title='screen#>' --command='/projects/cli/launchers/screen' \
	${argv} &;

