#!/usr/bin/env php
<?php
	ini_set( "display_errors", TRUE );
	ini_set( "error_reporting", E_ALL | E_STRICT );
	ini_set( "default_charset", "utf-8" );
	
	if(!(isset($_SERVER['argv'][1]))){
		printf("Usage: %s [\"string\"]\n", $_SERVER['argv']);
		exit -1;
	}
	
	printf( "%s", utf8_encode(html_entity_decode($_SERVER['argv'][1]) ));
?>

