#!/usr/bin/env php
<?php
	ini_set( "display_errors", TRUE );
	ini_set( "error_reporting", E_ALL | E_STRICT );
	ini_set( "date.timezone", "UTC" );
	printf( "%s", strftime("%d-%m-%Y", $_SERVER['argv'][1]) );
?>
