#!/usr/bin/env php
<?php
	ini_set( "display_errors", TRUE );
	ini_set( "error_reporting", E_ALL | E_STRICT );
	ini_set( "default_charset", "utf-8" );

	function usage($status=0){
		printf("Usage: %s [\"string\"] or -(to read from stdin)\n", $_SERVER['argv'][0]);
		exit($status);
	}/*usage();*/
	
	if(!isset($_SERVER['argv'][1]))
		usage(-1);
	else if( $_SERVER['argv'][1]=="-h" || $_SERVER['argv'][1]=="--help" )
		usage();
	
	if( "{$_SERVER['argv'][1]}" != "-" ){
		$data=$_SERVER['argv'][1];
		printf( "%s", urldecode($data) ));
		exit(0);
	}
	
	$data="";
	while(!feof(STDIN))
		while( $data=fread(STDIN, 1024)){
			printf( "%s", urldecode($data) ));
			$data="";
		}
	
	exit(0);
?>
