#!/bin/tcsh -f
if( ${?TCSH_RC_DEBUG} ) then
	if( ${?TCSH_OUTPUT_ENABLED} ) exit 1;
	unsetenv TCSH_RC_DEBUG;
	exit 0;
endif

@ debug=0;
#setenv TCSH_RC_DEBUG;
if( ${?TCSH_OUTPUT_DISABLED} ) \
	exit 0;
	
@ arg=1;
set argc=${#argv};
while( $arg < $argc )
	@ arg++;
	if( "$argv[$arg]" != "--debug" ) \
		continue;
	
	printf "[%s]: enabling verbose debugging output @ %s.\n" "$argv[0]" `date "+%I:%M:%S%P"`;
	setenv TCSH_RC_DEBUG "$argv[0]";
	@ debug=1;
	break;
endif
exit $debug;
