#!/bin/tcsh -f
if( ${?TCSH_RC_DEBUG} ) then
	if( ! ${?SSH_CONNECTION} ) exit 1;
	unsetenv TCSH_RC_DEBUG;
	exit 0;
endif

@ debug=0;
#setenv TCSH_RC_DEBUG;
if( ! ${?SSH_CONNECTION} && ${?1} && "${1}" != "" && ( ( ${?2} && "${2}" != "" && "${2}" == "--debug" ) || ( ${?3} && "${3}" != "" && "${3}" == "--debug" ) ) ) then
	printf "[%s]: enabling verbose debugging output @ %s.\n" "${1}" `date "+%I:%M:%S%P"`;
	setenv TCSH_RC_DEBUG "${1}";
	@ debug=1;
endif
exit $debug;
