#!/bin/tcsh -f
if( ! ${?TCSH_SESSION_RC_PATH} ) setenv TCSH_SESSION_RC_PATH "/projects/cli/tcshrc";
foreach path_source_file( ${argv} )
	if( ${?TCSHRC_DEBUG} ) printf "Sourcing ${TCSH_SESSION_RC_PATH}/${path_source_file}\n";
	source "${TCSH_SESSION_RC_PATH}/${path_source_file}";
end

